quay/claircore

- debian/fetch.go
- debian/matcher.go
- debian/matcher_integration_test.go
- debian/osrelease.go
- debian/releases.go
- debian/resolvevcn.go
- debian/resolvevcn_test.go
- debian/testdata/scanreport-buster-jackson-databind.json
- debian/updater.go
- debian/updater_integration_test.go
- dpkg/packagescanner.go
- internal/scanner/defaultscanner/scanner.go
- internal/vulnscanner/scanner.go
- internal/vulnstore/postgres/testvulnstore.go
- pkg/oval/links.go
- ubuntu/fetch.go
- ubuntu/resolvevcn.go
- ubuntu/resolvevcn_test.go
- ubuntu/updater.go
- ubuntu/vcnresolve.go
Adds Debian Oval XML support along with a new method of identifying Version Code Name more aggressively. 
Debian and Ubuntu CVE definitions use this os-release field to match vulnerabilities so an emphasis is made to identify it correctly. 
Draft PR to get comments.
> Debian support

- Makefile
- docker-compose.yaml
These commits make the development helpers populate a vendor directory and use them, instead of always downloading modules in the container.
> Makefile: use `go mod vendor`

- internal/vulnstore/postgres/bootstrap.sql
- internal/vulnstore/postgres/putvulnerabilities.go
We want to force unique constraints on vulnerability records to support tombstoning without large amounts of writes and deletes. 
We ran into an issue where the "description" column gets too large for the btree index.
This fix does an md5 hash on the "description" column when evaluating the unique index. The output of the md5 hash is now the index key.
> Updater: unique constraint size fix

- cmd/libvulnhttp/main.go
- oracle/oracle_test.go
- oracle/parser.go
- oracle/parser_test.go
- oracle/updater.go
- oracle/updater_test.go
- test/log/log.go
This commit fetches and parses the Oracle Linux oval database.
It also wires it into the dev server and adds the ability to run only
specific updaters to the dev server.
It also adds an adapter between testing.TB's logging methods and
zerolog.
> oracle: add Oracle Linux oval updater

- aws/client_test.go
PR fixes an issue where global vars that are hijacked for testing were not reset before integration tests were run. Integration tests expect the real Amazon mirror urls and thus blew up.
> swap mirrors back on test exit

- internal/scanner/defaultscanner/buildimageresult.go
- internal/scanner/defaultscanner/buildlayerresult.go
- internal/scanner/defaultscanner/checkmanifest.go
- internal/scanner/defaultscanner/scanfinished.go
- internal/scanner/defaultscanner/scanner.go
- internal/scanner/opts.go
- internal/scanner/versionedscanner.go
- libscan/factory.go
- libscan/libscan.go
- libscan/opts.go
Rebased ontop of data-model-changes. This PR implements the plumbing necessary for discrete Repository and Distribution scanners. Prior to this both Distribution and Package scanning was a facility of just a PackageScanner. 
A bunch of code cleanup occurred too which reduces the amount of copying between Libscan Opts and Scanner Opts.
> Libscan plumbing

- alpine/ecosystem.go
- cmd/libscanhttp/main.go
- internal/scanner/postgres/layerscanned.go
- osrelease/scanner.go
- rpm/ecosystem.go
PR plumbs ecosystems into libscan test http servers. 
Fixes the os-release scanner type to 'distribution'
> plumb ecosystems, fix os-release scanner type

- DCO
- LICENSE
We overlooked including a license file before publishing code.
All files in this repository with a Red Hat copyright are and
have been available under the license introduced in this commit.
> all: add license and dco

- Makefile
- cmd/libscanhttp/main.go
- cmd/libvulnhttp/main.go
- docker-compose.yaml
- libscan/controllerfactory.go
- libscan/init.go
- libscan/opts.go
- libvuln/init.go
- libvuln/libvuln.go
- libvuln/opts.go
- libvuln/updaters.go
Refactors most initialization logic back into each library. It began to leak a bit. 
Various refactoring to retrofit in ClairV4.
Removal of to-soon-abstraction on DataStore and dist lock types.
> consolidate initialization to lib construction

- ubuntu/matcher.go
- ubuntu/releases.go
- ubuntu/updater.go
This PR implements Ubuntu vulnerability matching. 
PR uses the VersionID field in the os-release file to match parsed vulnerabilities with package distributions.
> Ubuntu Matching

- cmd/cctool/inspector.go
- cmd/cctool/main.go
- cmd/cctool/report.go
This adds a rough tool for interacting with the servers in this module.
It's meant to be driven from a script like so:
```report.sh
#!/bin/sh
set -e
list="
docker://registry.access.redhat.com/ubi8/ubi:8.0-122
"
for i in $list; do
if echo "$i" | grep -qv mynamespace; then
tgt="docker://myquay/mynamespace/${i##docker://*/}"
skopeo copy -q "$i" "$tgt"
i="$tgt"
fi
printf %s\\n "$i"
done | cctool \
-f 'https://storagehost/datastorage/registry/sha256/{{printf "%.2s" .Hash}}/{{.Hash}}' \
report
```
The documentation is... scant, but the `-h` flags work.
> cctool: add a tool for interacting with claircore directly

- alpine/matcher.go
- aws/matcher.go
- debian/matcher.go
- internal/matcher/matcher_mock.go
- libvuln/driver/driver.go
- ubuntu/matcher.go
Adds a interface method to extract a Name from an instantiated Matcher. 
@hdonnay you can merge this and rebase #69 to remove the reflection.
> add Name interface method to Matcher

- alpine/matcher.go
- aws/matcher.go
- debian/matcher.go
- internal/vulnstore/postgres/get.go
- internal/vulnstore/postgres/querybuilder.go
- internal/vulnstore/postgres/querybuilder_test.go
- libvuln/driver/driver.go
- rhel/matcher.go
- ubuntu/matcher.go
This PR removes the legacy naming for match Exps. Dist info is now decoupled from packages and this is now demonstrated
> Rename match exps 

- suse/suse.go
This PR flips SUSE's sec db from ftp to https site. FTP seems to no longer work.
> swap suse to https

- environment.go
- internal/matcher/match.go
- vulnerabilityreport.go
This PR changes any ids used for "lookup" to strings. The resulting map keys for Packages, Distributions, Vulnerability fields in an IndexReport or Vulnerability reports will be transformed to strings. This makes lookups work correctly.
> lookup ids to strings

- internal/indexer/postgres/distributionsbylayer.go
- internal/indexer/postgres/layerscanned.go
- internal/indexer/postgres/manifestscanned.go
- internal/indexer/postgres/packagesbylayer.go
- internal/indexer/postgres/registerscanners_test.go
- internal/indexer/postgres/repositoriesbylayer.go
- internal/indexer/postgres/setindexfinished.go
- internal/indexer/postgres/setindexfinished_test.go
- libindex/migrations/migration1.go
- libvuln/migrations/migration1.go
This commit changes the DDL to use bigserials and bigints for IDs, and any
code where ids are being read out of the database is updated to use go's
int64 type.
> all: use bigserials in the database

- internal/vulnstore/postgres/get.go
- internal/vulnstore/postgres/querybuilder.go
- internal/vulnstore/postgres/querybuilder_test.go
results in reports with vulnerabilities like:
"410835": {
"description": "A Bleichenbacher type side-channel based padding oracle attack was found in the way nettle handles endian conversion of RSA decrypted PKCS#1 v1.5 data. An attacker who is able to run a process on the same physical core as the victim process, could use this flaw extract plaintext or in some cases downgrade any TLS connections to a vulnerable server.",
"fixed_in_version": "",
"id": "410835",
"links": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-16869 http://people.canonical.com/~ubuntu-security/cve/2018/CVE-2018-16869.html http://cat.eyalro.net/ https://lists.lysator.liu.se/pipermail/nettle-bugs/2018/007363.html https://lists.debian.org/debian-lts/2019/03/msg00021.html",
"name": "CVE-2018-16869", …
> postgres: retrieve updater informaition

- cmd/cctool/main.go
- cmd/cctool/manifest.go
- docs/SUMMARY.md
- docs/contributor.md
- docs/contributor/cctool.md
This adds a subcommand to cctool that just emits claircore manifests on stdout.
> cctool: add "manifest" subcommand

- Makefile
Small fix which allows for `make claircore-db-restart` to destroy the current db and create a new one correctly.
> fix db recreate

- go.mod
- go.sum
- internal/indexer/postgres/teststore.go
- internal/vulnstore/postgres/testvulnstore.go
This PR bumps go-cmp to remove a race detector bug and fixes up some
go1.14 error formating issues
This PR bumps go-cmp to latest version and voids a race detector test
> Bump Go-Cmp

- alpine/distributionscanner.go
- aws/distributionscanner.go
- debian/distributionscanner.go
- internal/indexer/layerscanner/layerscanner.go
- oracle/distributionscanner.go
- rhel/distributionscanner.go
- suse/distributionscanner.go
- ubuntu/distributionscanner.go
This PR fixes an issue where distro scanners were returning an empty
struct when the os-release file was found, but was not able to be parsed 
by the distribution scanner.
> distro scanner fixes

- libindex/handler.go
- libindex/libindex.go
This PR makes the state endpoint look like the others.
This also fixes an issue where you cannot create an interface that wraps
libindex easily due to usually wanting ctx and an error when
implementing a remote service
> make state method consistent

- scanner/pkgconfig/scanner.go
- scanner/pkgconfig/scanner_test.go
- scanner/pkgconfig/testdata/bash-completion.pc
- scanner/pkgconfig/testdata/dracut.pc
- scanner/pkgconfig/testdata/libpng.pc
- scanner/pkgconfig/testdata/shared-mime-info.pc
- scanner/pkgconfig/testdata/systemd.pc
- scanner/pkgconfig/testdata/udev.pc
This change adds a scanner that looks for pkg-config
(https://www.freedesktop.org/wiki/Software/pkg-config/) files in layers.
This isn't wired up yet, because there's some planning to be done around
how this interacts with packages that will be picked up by a more
precise means, like a package manager.
> pkgconfig: add pkg-config scanner

- pkg/fastesturl/fastesturl.go
- pkg/fastesturl/fastesturl_test.go
This commit changes the tests to sequence responses without using
sleeps.
Over the course of testing, using high counts caused the tests to hang.
I ended up restructuring the internals to fix that.
> fastesturl: deflake the test

- .gitignore
- python/matcher.go
- python/packagescanner.go
- python/packagescanner_test.go
- pyupio/updater.go
The image `ararunprasad/flask-0.12` has vulnerable Flask version 0.12 , but it is not flagged by Claircore due to case-sensitive name comparison.
```
./cctool report ararunprasad/flask-0.12
```
Actually I couldn't write a test for this fix because the package name equality has been done through SQL query. Correct me If I'm wrong.
> Make python package name case insensitive 

- go.mod
- internal/indexer/postgres/bootstrap.sql
- internal/indexer/postgres/indexpackage.go
- internal/indexer/postgres/packagesbylayer.go
- libindex/migrations/migration1.go
- package.go
- rpm/packagescanner.go
- test/package.go
- test/postgres/package.go
Module property stores information about package module and stream which
the package is part of.
This is mostly used for modular rpm content. Rpm parser gets module
info from RPMTAG_MODULARITYLABEL in rpm database.
> Add module property to Package

- photon/photon.go
photon artifacts publish had a change. this change is final. 
updating url change.
> update photon security url to new location

- internal/indexer/fetcher/fetcher.go
PR adds a uri element to fetcher's logger context
> add fetch uri log

- docker-compose.yaml
I like to keep firewalld enabled on my fedora machine.
Docker compose creates a user defined network and usually the linux bridge interface it creates has a random name and this makes it difficult to place into firewalld zone rules.
This PR makes the local-dev linux bridge interface hosting the local dev network a consistent name. 
> add consistent linux bridge name

- .gitignore
- cmd/cctool/main.go
- cmd/cctool/unpack.go
- layer.go
This PR implements a command to unpack a particular image reference to your temp directory.
I keep having to do this when detection fails for a particular image and this slipstreams that process
> CCTool Unpack

- aws/client.go
- aws/updater.go
- internal/indexer/ecosystem.go
- internal/indexer/layerscanner/layerscanner.go
- internal/indexer/layerscanner/layerscanner_test.go
- internal/indexer/opts.go
- internal/indexer/versionedscanner.go
- libindex/controllerfactory.go
- libindex/libindex.go
- libindex/opts.go
These configuration knobs lay the groundwork for having scanners that are configurable and make RPCs, and for making updaters that are configurable.
I'd be fine with dropping the `alpine` commit out of this stack, it's there as a PoC.
> Configuration groundwork

- internal/vulnstore/postgres/getupdateoperationdiff.go
- internal/vulnstore/postgres/getupdateoperations.go
- internal/vulnstore/postgres/update_e2e_test.go
- libvuln/driver/updatediff.go
This also normalizes the json names of the update structures.
> updatediffs: fix broken query, add cctool subcommand

- cmd/cctool/unpack.go
- rpm/packagescanner.go
In some cases tar command fails with permission error. This option
avoids those errors.
https://changilkim.wordpress.com/2013/12/30/tar-cannot-mkdir-permission-denied/
> Add --delay-directory-restor option to tar command

- archop.go
- archop_string.go
- internal/vulnstore/postgres/update_e2e_test.go
- libvuln/migrations/migration1.go
- osrelease/scanner_test.go
- pkg/ovalutil/rpm.go
- vulnerability.go
This PR fixes a regression in matching.
> arch op: turn into string, implement pattern match

- alpine/fetcher_test.go
- alpine/packagescanner_test.go
- alpine/parser_test.go
- aws/updater_integration_test.go
- debian/matcher_integration_test.go
- debian/updater_integration_test.go
- dpkg/scanner_test.go
- internal/indexer/controller/controller_test.go
- internal/indexer/fetcher/fetcher_test.go
- internal/indexer/linux/coalescer_test.go
- internal/indexer/postgres/affected_manifests_e2e_test.go
- internal/indexer/postgres/indexpackage_benchmark_test.go
- internal/indexer/postgres/packagesbylayer_benchmark_test.go
- internal/vulnstore/postgres/update_e2e_test.go
- libindex/libindex_integration_test.go
- oracle/parser_test.go
- oracle/updater_test.go
- osrelease/scanner_test.go
- photon/integration_test.go
- pyupio/updater_test.go
- rhel/coalescer_test.go
- rhel/fetch_test.go
- rhel/matcher_test.go
- rhel/parse_test.go
- rhel/repositoryscanner_test.go
- rpm/packagescanner_test.go
- suse/integration_test.go
- test/log/log.go
- test/packagescanner.go
This change introduces a child context and explicitly closing the write
end of the pipe. It should catch the situation where a line could be
being written after the Context was cancelled and the test returned.
> log: one more attempt at race squashing

- libvuln/opts.go
For integration testing purposes we should be able to point claircore to
different oval stream using env var.
> Add ability to override oval v2 using env var

- Makefile
- docker-compose.yaml
- etc/podman.yaml.in
PR creates consistent container names so local dev does not break between git worktrees.
> consistent conainter names

- libvuln/opts.go
- pkg/omnimatcher/omnimatcher.go
- pkg/ovalutil/rpm.go
- rhel/containerapi/containerapi.go
- rhel/ecosystem.go
- rhel/matcher.go
- rhel/parser.go
- rhel/repositoryscanner.go
- rhel/repositoryscanner_test.go
The previous implementation of CPE mapping in the matcher has a lot of corner cases. So we decided to put a mapping code into indexer instead. Mapping is fetched in the background in regular intervals and it is used during repo scan.
This pull request also contains several changes that fixed rhel matching.
> CPE mapping in indexer + rhel matching changes

- internal/vulnstore/postgres/querybuilder.go
- internal/vulnstore/postgres/querybuilder_test.go
By adding package kind to database vulnerability query we query only
real affected packages. Without this code Clair produce false negatives
in case source package and binary package has same name.
When vulnerability is issued with source package all binary package that
have come from same source are marked as vulnerable.
> Add package_kind to vulnerability query

- debian/parser.go
- debian/updater.go
- go.mod
- go.sum
- oracle/parser.go
- photon/parser.go
- pkg/ovalutil/dpkg.go
- pkg/ovalutil/rpm.go
- rhel/parser.go
- suse/parser.go
- ubuntu/parser.go
- ubuntu/updater.go
This PR implements correct OVAL parsing for debian and ubuntu moving
away from incorrect regex parsing of the oval data.
goval-parser is bumped to obtain the necessary datastructures.
> Implement oval parsing for debian and ubuntu

- Makefile
- internal/indexer/linux/coalescer.go
- internal/indexer/linux/coalescer_test.go
- internal/indexer/linux/distsearcher.go
- internal/indexer/linux/packagesearcher.go
- internal/indexer/postgres/indexmanifest.go
- libvuln/libvuln.go
This PR refactors the coalescer into a set of data structures working together. This as prompted by:
Jira:  PROJQUAY-995
Closes: #213
I am seeing analysis no longer includes older packages once upgraded. 
old-coalescer:
```
mitmproxy:4.0.1 found musl    1.1.18-r2 CVE-2019-14697 (fixed: 1.1.18-r4)
mitmproxy:4.0.1 found expat   2.2.5-r0  CVE-2018-20843 (fixed: 2.2.7-r0)
mitmproxy:4.0.1 found expat   2.2.5-r0  CVE-2019-15903 (fixed: 2.2.7-r1)
mitmproxy:4.0.1 found openssl 1.0.2o-r0 CVE-2019-1563  (fixed: 1.0.2t-r0)
mitmproxy:4.0.1 found openssl 1.0.2o-r0 CVE-2019-1547  (fixed: 1.0.2t-r0)
mitmproxy:4.0.1 found openssl 1.0.2o-r0 CVE-2019-1559  (fixed: 1.0.2r-r0)
mitmproxy:4.0.1 found openssl 1.0.2o-r0 CVE-2018-0737  (fixed: 1.0.2o-r1)
mitmproxy:4.0.1 found openssl 1.0.2o-r0 CVE-2018-0732 …
```
> coalescer: refactor of the linux coalescer

- internal/vulnstore/postgres/update_e2e_test.go
- internal/vulnstore/postgres/updatevulnerabilities.go
Previously, this table could grow without bound, which is suboptimal.
> postgres: manage the number of update_operations

- pkg/ovalutil/fetcher.go
- rhel/updaterset.go
Sometime E-tag doesn't work as expected so adding last-modified makes
sure we don't update same file multiple times if it hasn't changed.
> RHEL: Use last-modified to cache data

- docker-compose.yaml
When setting up local dev environment on SELinux-enabled system, `libindexhttp` and `libvulnhttp` containers exit with error code and "Permission denied" in log. This is because by default a repository cloned into your home does not have the SELinux type required by docker. This can be solved by adding `z` suffix to the volume mount. Docker then takes care about applying the proper SELinux type to the mounted volume. More info [here](https://prefetch.net/blog/2017/09/30/using-docker-volumes-on-selinux-enabled-servers/).
It seems that this does not negatively affect non-SELinux systems. Adam tested it on Arch Linux and no problems were encountered. However, if someone else can also verify on non-SELinux OS, it would be great.
> Makefile: handle SELinux permissions for volume in docker-compose

- rpm/packagescanner.go
Packages database is only file that is necessary for getting list of
installed rpms. Other files makes query more efficient.
This commit was created based on couple of images where some rpm
database file were missing and rpm scanner skipped the database.
> rpm: Reduce database file to Packages + fix race condition

- internal/vulnstore/postgres/getupdateoperationdiff.go
this commit puts a limit on the number of returned vulnerabilities when
diffing two update operations.
Signed-off-by: ldelossa <ldelossa@localhost.localdomain>
> vulnstore: limit diffs

- internal/indexer/layerscanner/layerscanner.go
It seems like during a refactor, this function started getting called
unconditionally. The new behavior was still correct, but the warning log
line was then emitted unconditionally.
> layerscanner: prevent misleading log line

- pkg/ovalutil/rpm.go
The cache structure didn't work as expected in some cases. Cache key was
made of package name and module, but Package structure has much more
fields that may affect cache hit/miss. By removing this cache we fix the
bug that incorrectly filled Package with other properties.
This bug was discovered because architecture of some packages was
incorrectly overridden by package from different vulnerability.
> Remove cache from oval rpm parser

- internal/indexer/postgres/affectedmanifest.go
This commit removes the warning message in the case where the system knows
of a vulnerability but doesn't know of any manifests that it could apply to.
> postgres: remove warning in common case

- internal/updater/controller.go
This would result in a subtle bug where the Mutex would get copied, but
because the map builtin has an internal pointer, as long as the map
didn't re-allocate the updates would show up and as long as the writes
weren't concurrent, the map race detector wouldn't trip.
> updater: use pointer receiver for errmap methods

- internal/indexer/postgres/affectedmanifest.go
- internal/vulnstore/postgres/getupdateoperationdiff.go
- internal/vulnstore/postgres/scan_vulnerability.go
- pkg/omnimatcher/omnimatcher.go
The pull request fixes 2 bugs in omnimatcher logic.
Add missing properties into affected manifest query
These properties were missing in queries that search for affected
manifest which caused incorrect API response.
-----
Use mather's Filter() in omnimatcher. 
The previous implementation used all matchers to find out whether
package is vulnerable. This approach didn't work because each matcher is
interested only in specific subset packages given by mather's filter.
This commit adds filer to omnimatcher to make sure only the right matchers
are used.
> Affected manifest: Update query and logic that determines afected manifests

- pkg/ovalutil/dpkg.go
- pkg/ovalutil/rpm.go
- rhel/parse_test.go
Lookup() function returns a object based on reference ID in all
sub-structures. This can cause that object that is returned can have a
different type than module requires.
This commit add checks to rpm and dpkg module to Lookup only properties
specific to the module.
> Oval: check lookup type

- libvuln/libvuln.go
this removes the case where a single updater error kills the long
running update loop
> updaters: do not kill loop on error

- pyupio/testdata/db_meta.json
- pyupio/updater.go
- pyupio/updater_test.go
Upstream denormalized the data, so this handles the magic key.
> pyupio: handle database schema change

- etc/podman.yaml.in
Previous versions of the postgres container were happy to have the sever
run as root, but the new entrypoint drops permissions. The generated
yaml enshrined not using the container's entrypoint. This commit undoes
that.
> etc: update podman yaml

- internal/vulnstore/postgres/getupdateoperationdiff.go
The limit can be removed because it is no longer needed and not having a
limit didn't cause issues as we thought at a beginning.
> updater: remove updater diff limit

- .github/workflows/prepare-release.yml
- .github/workflows/release.yml
commit removes deprecated set-env from github actions
> cicd: github actions set-env fix

- docs/contributor/logging.md
- docs/getting_started/libvuln_usage.md
Just fixing a couple of typos I found when reading the docs today.
Verified by running `mdbook serve` locally
> docs: fix couple typos in libvuln_usage.md

- .github/workflows/main.yml
Get CI images from quay.io instead of DockerHub. This is related to https://github.com/quay/clair/pull/1138.
> cicd: use CI golang image from quay.io

- rhel/updaterset.go
See the comment above the exception for explanation of this PR.
There was also an alternate approach: Creating 
```go
var ignoredStreams = []string{
"RHEL7-rhel-7-alt",
}
```
and then checking for each image whether it is ignored or not. Even though this would be better from maintainability point of view, I decided to go for this simple approach. It's mainly because:
- This will save a lot of iterations
- With high probability there'll be no other ignored stream
> Add exception for rhel-7-alt OVAL stream

- .github/workflows/main.yml
Unfortunately it seems we need to go back to DockerHub image as app-sre image has become private. 
This reverts commit 97fa28bcb92a7b0db1b15cfb6cc45bd678d3f268.
Signed-off-by: Jan Zmeskal <jzmeskal@redhat.com>
> Revert "cicd: use CI golang image from quay.io"

- cmd/libvulnhttp/main.go
This option is useful when you develop `libvuln` library, want to keep it running but don't want regular updates to get in your way.
Signed-off-by: Jan Zmeskal <jzmeskal@redhat.com>
> libvulnhttp: add DisableBackgroundUpdates config option

- internal/indexer/controller/checkmanifest.go
- internal/indexer/postgres/manifestscanned.go
This commit adds a filtering step in the CheckManifest state.
Now, if a manifest reports being analyzed by a particular scanner that
scanner will be omitted from all subsequent states.
This is safe to do, if a manifest was analyzed by a particular scanner,
this also means all it's layers were analyzed by the particular scanner.
Thus, the scanner need not be included in the rest of the indexing
process.
This fixes a unique constraint issue in the IndexFinished state.
Previous to this commit, an attempt to persist duplicate scanner ids was
made in the aforementioned state.
> indexer: filter scanners during manifest check

- libvuln/jsonblob/jsonblob.go
- libvuln/jsonblob/jsonblob_test.go
- libvuln/libvuln.go
- libvuln/opts.go
- libvuln/updates/manager.go
- libvuln/updates/options.go
this commit consolidates updater filtering, getting defaults from the
registry, configuring factories, configuring updaters, and running
updaters in a loop into a single cohesive unit.
> updaters: consolidate into manager

- internal/indexer/controller/controller.go
- internal/indexer/controller/indexfinished.go
- internal/indexer/controller/state.go
- internal/vulnstore/postgres/store.go
- libindex/opts.go
- libvuln/handler.go
Fix error responses of `UpdateOperations` handler. The only real change in this PR is in `libvuln/handler.go`. The rest are just typos I encountered when studying the code.
> postgres: fix update_operation response

- .github/workflows/main.yml
- etc/Dockerfile
This is my latest attempt to remove dependency on DockerHub golang image. Here's the basic idea behind this:
- I noticed that there's already existing quay.io/claircore/golang image
- That image is already used by docker-compose files both in this repo and in quay/clair
- In this repo, we have a very easy-to-use make target to build that image
Given all of this, I though to myself: Why not just use this image at other places beyond docker-compose as well?
Here's what I did to make it work:
- I added `git` package to the Dockerfile we use to build the quay image. As far as I can tell, that was the only thing missing there
- I rebuild and pushed all the tags we require (1.13, 1.14, 1.15, 1.15.2)
- I changed container in 'tidy' job to quay.io/claircore/golang:1.15. We used to point at …
> cicd: use quay.io/claircore/golang in CI

- libvuln/updates/options.go
previous to this commit the WithEnabled option did not implement the
tristate necessary when configuring updaters.
> updaters: fix WithEnabled option

- .github/workflows/release.yml
previous to this commit the env var TAG was being used inplace of the
correct var VERSION when generating release change log.
> cicd: fix release notes

- crda/normalizeseverity.go
- crda/remotematcher.go
- crda/remotematcher_test.go
- crda/testdata/pypi/flask/0.12.json
- crda/testdata/pypi/pyyaml/5.3.json
This supplements https://github.com/quay/claircore/pull/202.
> remotematcher: Implement RemoteMatcher for CRDA

- cmd/libvulnhttp/main.go
- internal/vulnstore/postgres/store.go
the previous query took an absurd amount of time to complete.
updated with a more performant query.
> vulnstore: fix gc live lock

- libindex/controllerfactory.go
With the default number of connections controller pool can make set to 4, indexer tends to get quite greedy and might bully matcher and notifier. For in-depth discussion of this issue, see #308
> libindex: limit MaxConns in controller pool to 1

- rhel/repo2cpe/updater.go
this commit makes sure a nil pointer of type *repo2cpe.MappingFile is
loaded into the atomic.Value.
type assertions of the atomic.Value should never fail after this.
Loads() of the atomic.Value before a mapping file is downloaded should
return a typed nil.
> rhel: fix cpe mapping type assertion

- rhel/repo2cpe/updater.go
this commit makes sure a nil pointer of type *repo2cpe.MappingFile is
loaded into the atomic.Value.
type assertions of the atomic.Value should never fail after this.
Loads() of the atomic.Value before a mapping file is downloaded should
return a typed nil.
> [v0.1 Backport] rhel: fix cpe mapping type assertion 

- cmd/libvulnhttp/main.go
- internal/vulnstore/postgres/gc.go
- internal/vulnstore/postgres/gc_test.go
- internal/vulnstore/postgres/store.go
- libvuln/migrations/migration2.go
- libvuln/migrations/migrations.go
- libvuln/updates/manager.go
this commit moves to a chunking strategy for cleaning up
vulnerabilities.
the previous methods take too long to complete on our largest two
tables.
> vulnstore: chunked vuln cleanup

- internal/indexer/fetcher/fetcher.go
Docker Manifest v2s2 defines
`application/vnd.docker.image.rootfs.diff.tar.gzip` as the media type for
layers, and apparently some registries use this when serving layer
blobs. This was failing the heuristic based on the OCI media types and
traditional MIME types.
Closes #303
> fetcher: relax allowable gzip types

- libindex/libindex.go
This log is annoying and serves no real actionable purpose. Let's kill
it.
> libindex: remove annoying log

- crda/matcherfactory.go
- crda/remotematcher.go
- crda/remotematcher_test.go
- libvuln/driver/matcherfactory.go
- libvuln/libvuln.go
- libvuln/opts.go
- matchers/defaults/defaults.go
- matchers/matchers.go
- matchers/options.go
- matchers/registry/registry.go
This PR implements factory with registry pattern for matchers to facilitate passing configurable parameters to matchers.
> matchers: provide a way to pass config

- .chglog/config.yml
- .github/workflows/prepare-release.yml
- .github/workflows/release.yml
since we interleave back-port releases with
mainline, we need to order our change log
by semver to ensure our changes merge correctly.
right now this uses a fork of git-chglog which
implements this semver-ordering.
if this PR merges: https://github.com/git-chglog/git-chglog/pull/124
we will no longer utilize the fork and pull git-chlog upstream latest
> cicd: sort changelog by semver

- .github/workflows/release.yml
copy pasta of cicd jobs causes a bad
path lookup for the git-chglog tool.
> cicd: fix release failure

- rhel/matcher.go
- rhel/matcher_test.go
Red Hat Product Security will be enriching content of OVAL streams. Soon they'll also contain know vulnerabilities without published fix. This change enables us to treat vulnerabilities that don't have `FixedInVersion` field as unfixed.
> rhel: treat vulns without FixedInVersion as unfixed

- python/packagescanner.go
This makes it so the changes in 2cef538 cause layers to get re-scanned
and re-matched.
> python: update package scanner version

- libvuln/migrations/migration3.go
- libvuln/migrations/migrations.go
recent changes to the python updater were made but
pyup databse updates slowly.
this migration forces a re-fetch/parse of the pyup
database, fixing python matching in the upgrade path.
> python: force re-fetch/parse

- .github/workflows/update.yml
updates the gh action for building docs to
fire on pushes to main instead of master.
necessary due to master -> main rename done on this date.
> cicd: update doc building to main

- pkg/ovalutil/rpm.go
- pkg/ovalutil/rpm_test.go
- rhel/parser.go
This PR comlements #338 and since this one isn't as straightforward, I think it's a good time to dive in and explain broader context of these two changes. 
Red Hat Product Security is planning to release new version of OVAL data. The main difference will be addition of `<affected_cpe_list>` to definitions of class "vulnerability". There are two types of such definitions in OVAL files, distinguished by the format of their ID.
Example (Example are only from testing data. Their content might have been edited for testing purposes, what matters here is the format):
```xml
<definition class="vulnerability" id="oval:com.redhat.cve:def:20162166" version="634">
<metadata>
<title>CVE-2016-2166 qpid-proton: reactor sends  messages in clear if ssl is requested but not available (moderate)</title> …
```
> rhel: discard unaffected vulnerabilities

- crda/matcherfactory.go
- crda/remotematcher.go
- crda/remotematcher_test.go
- libvuln/driver/matcherfactory.go
- matchers/matchers.go
This PR adds the ability to return multiple matchers from single matcherfactory.
Signed-off-by: Arunprasad Rajkumar <arajkuma@redhat.com>
> matcher: add ability to return multiple matchers from a factory

- test/integration/db.go
When running integration tests locally, acquiring the advisory locks will exhaust the `maxConns`, meaning any subsequent DB transactions will hang. Here are the relevant rows from Postgres pg_stat_activity:
```
db5a7e55f57007bc0e=> SELECT 
pid               
,datname
,usename
,application_name
,client_hostname
,client_port
,backend_start
,query_start
,query
,state
FROM pg_stat_activity
WHERE state = 'idle in transaction';
pid  |      datname       |       usename       | application_name | client_hostname | client_port |         backend_start         |          query_start          |                 query                 |        state        
-------+--------------------+---------------------+------------------+-----------------+-------------+-------------------------------+-------------- …
```
> testing: maxConns to 10

- libindex/libindex.go
- libindex/libindex_test.go
This concurrency pattern may help with DB load, particularly burst load. Instead of starting 100 goroutines, waiting for them to all finish, then firing off 100 more, this change will block creating new goroutines until a currently running one has returned. 
This means you aren't waiting for the slowest routine in every 100. In this case, where it's a DB lookup with the same query, all the routines probably complete within a similar time bound, but it may help spread the DB load rather than being spikey.
TODO
> [WIP] Bounded concurrency affected manifests

- pkg/cpe/json.go
- version.go
Here's a short test program to prove the change does the right thing:
https://play.golang.org/p/wM6S9H83E2v
Fixes [PROJQUAY-1918](https://issues.redhat.com/browse/PROJQUAY-1918).
> all: return empty byte slices from MarshalText

- libvuln/migrations/migration4.go
- libvuln/migrations/migrations.go
This commit adds the necessary migration to support the Enrichment feature
per out specification: https://github.com/quay/clair-enrichment-spec/
Backports: bfafd2f7ad2b4d4b33fb0ab644bb09191d42732c
> vulnstore: enrichment migration backport

- docker-compose.yaml
Signed-off-by: Jan Zmeskal <jzmeskal@redhat.com>
> cicd: use golang major version tag for dev env

- libindex/libindex.go
- libindex/migrations/migration3.go
- libindex/migrations/migrations.go
This commit adds a migration to fix the missing unique constraint on
the `manifest_index` table. Without this constraint, the
`manifest_index` table can bloat to absurd size.
In order to deal with tables which have already bloated to absurd size,
we simply truncate the `manifest_index` table. We also truncate the
`manifest_scanned` table which allows all subsequent manifests submitted
to clair to be re-indexed.
This re-index will rebuild the `manifest_index` for the manifest being
submitted, but perform no other work since all layer data still exists
for a previously seen manifest.
> libindex: fix manifest_index unique constraint

- dpkg/scanner.go
- dpkg/scanner_test.go
- test/fetch/layer.go
This fixes a bug reported via #381 where paths weren't normalized the
same way after reading the names from the tar header.
Closes #381.
> dpkg: fix path handling

- dpkg/scanner.go
This fixes a bug reported via #381 where paths weren't normalized the
same way after reading the names from the tar header.
This backports #402 without the accompanying test, due to fetcher
changes.
> v0.1 backport: dpkg: fix path handling

- dpkg/scanner.go
- dpkg/scanner_test.go
- test/fetch/layer.go
This fixes a bug reported via #381 where paths weren't normalized the
same way after reading the names from the tar header.
This backports #402.
> v0.4 backport: dpkg: fix path handling

- java/common.go
- java/packagescanner.go
- java/reposcanner.go
As described in the OCI image [spec][1], whiteout files are used to
indicate file or directory removals. The jar scanner was not considering
file prefixes and instead only looking at the suffixes.
[1]: https://github.com/opencontainers/image-spec/blob/master/layer.md#representing-changes
> java: ignore whiteout files

- libindex/controllerfactory.go
- libindex/init.go
- libindex/libindex.go
This change instanciates the DB and passes the pool
around to who needs it. It also introduces a factory function
to create new locks as and when needed (with the same resources)
> indexer: avoid creating a new db pool for the locks

- internal/indexer/layerscanner/layerscanner.go
- internal/vulnstore/postgres/gc.go
- libvuln/updates/manager.go
- ubuntu/updaterset.go
When running directly on an OS, these values will be the same. But in
containerized environments, the number of CPUs reported is the number on
the host, not the number allocated. Using the GOMAXPROCS means the
container orchestrator can configure things such that the go runtime is
less likely to constantly blow its cpu quota.
> all: use GOMAXPROCS instead of NumCPU

- internal/vulnstore/postgres/getupdateoperations.go
This commit fixes query in GetLatestUpdateRefs which instead of
vulnerabilities was looking for enrichments.
Signed-off-by: Jakub Vulgan <jvulgan@redhat.com>
> postgres: fix query in GetLatestUpdateRefs

- dpkg/scanner.go
- go.mod
- go.sum
The package github.com/tadasv/go-dpkg was used in the dpkg package, and
it went unnoticed that it doesn't have a valid license. This removes it
and replaces the functionality.
> dpkg: replace go-dpkg dependency

- test/integration/db_init.go
- test/integration/engine.go
- test/integration/fixup_darwin.go
- test/integration/fixup_linux.go
- test/integration/fixup_other.go
- test/integration/lock_unix.go
- test/integration/lock_windows.go
- test/integration/run.go
- test/integration/skip.go
Some linux-specific usage of the syscall package was added with the
embedded postgres addition. This splits out and cordons off all the
syscall usage so that this package builds on linux, darwin, and windows
again.
> integration: multiple OS support

- test/integration/db_init.go
- test/integration/engine.go
- test/integration/fixup_darwin.go
- test/integration/fixup_linux.go
- test/integration/fixup_other.go
- test/integration/lock_unix.go
- test/integration/lock_windows.go
- test/integration/run.go
- test/integration/skip.go
Some linux-specific usage of the syscall package was added with the
embedded postgres addition. This splits out and cordons off all the
syscall usage so that this package builds on linux, darwin, and windows
again.
This backports #418
> backport-v0.5: integration: multiple OS support

- libindex/controllerfactory.go
- libindex/init.go
- libindex/libindex.go
This change instantiates the DB and passes the pool
around to who needs it. It also introduces a factory function
to create new locks as and when needed (with the same resources).
Backports #408
> backport: indexer: avoid creating a new db pool for the locks

- rpm/packagescanner.go
- rpm/packagescanner_test.go
The behavior of chmod(2) is more subtle than it really should be.
During our permissions fixup pass, if the target of a symlink was in a
directory not fixed yet (or in system's root) calling chmod on it will
attempt to change the mode bits on a file the process won't have
permissions for. The amount of corner cases in "remove this directory
and its contents" is annoying.
Backports: #424
> rpm: special-case symlinks

- rpm/packagescanner.go
- rpm/packagescanner_test.go
The root of permission errors seems to be from directories not being
writable. This isn't an issue for root, since they're allowed to touch
files however they like no matter what (assuming no xattrs are at play
-- I really hope they're not).  However, when a normal user extracts a
tarball, they can take away their own write bit, which must be added to
remove any files (i.e. write the dirent).
This is compounded by the behavior of `chmod`, which is to operate on the target.
If the walk hasn't fixed the directory of the target yet, it will fail.
> rpm: permissions madness

- .github/workflows/golang-image.yml
- etc/Dockerfile
Added platform check in the Dockerfile to download GO binary according to the host platform, and added buildx utility to the golang-image.yml file to release golang for both AMD64 and ARM64.
Signed-off-by: odidev <odidev@puresoftware.com>
> Release "quay.io/projectquay/golang" Docker Image for Linux/ARM64

- rpm/packagescanner.go
This commit removes the external call to tar and replaces it with
creating files directly.
The original motivation for the tar call was that recreating the correct
permissions for everything is tricky. I now realize we most certainly do
*not* want to recreate the permissions of the filesystem, because
they're frequently bonkers and require extra work to clean up properly.
The simplified extraction routine implemented here makes sure that all
files remain readable and writable by the user creating them, so that
the Clair process can actually remove them. Any additional PRs to this
logic to support things like BSD suid/guid directory logic will send me
into my cups.
Closes: #436
> rpm: remove tar(1) call

- java/packagescanner.go
I forgot to increment this when adding the `peek` function. Without it,
layers that failed due to phony jars will never get picked back up.
See-also: #435
> java: bump scanner version

- java/common.go
- java/packagescanner.go
- java/reposcanner.go
> Backport 0.4: java

- dpkg/scanner.go
The current way to identify a dpkg DB can be too
exclusive in some scenarios and the "available" dir
does not always exist. This change checks the info
dir is there. This could result in some more false
positives given how generic the names are but this
is highly unlikely to lead to false positives due
to DB file format we expect.`
> dpkg: update identification method of dpkg DB dir

- .github/scripts/get-latest-golang-minor-version.sh
Previously checking for the first major version would
yield something like 1.17.0, Go will refer to it as 1.17
hence the URL generated would 404
(https://dl.google.com/go/go1.17.0.linux-arm64.tar.gz).
> chore: Improve check for go versions

- libvuln/migrations/migrations.go
- libvuln/migrations/migrations5.go
Right now the GC can error out with a violates foreign key constraint
when trying to delete entries in the update_operations table as
this table references it in a foreign key.
> gc: add foreign key ON DELETE CASCADES to uo_enrich table

- rpm/packagescanner.go
Logically, cross-layer links are allowed, although we hadn't run across
them in testing.
Because layers are defined to be applied in-order, a container runtime
-- which never extracts layers in isolation -- never runs into this
issue and rightly errors out when attempting to link to a nonexistent
file. Clair's use case means the program should link to an empty file,
which needs to exist on the same filesystem. The file being empty should
be okay, because the contents will be seen in a different index.
There may be an edge case where the layer dodges all the indexers by not
having the "right" name in a lower layer and linking it in a higher
layer. I don't think this is avoidable.
Backports: #465
(cherry picked from commit …
> backport: rpm: handle cross-layer hardlinks when extracting

- libvuln/migrations/migrations.go
- libvuln/migrations/migrations5.go
Right now the GC can error out with a violates foreign key constraint
when trying to delete entries in the update_operations table as
this table references it in a foreign key.
Backports: #470
(cherry picked from commit 056d5e7956c798b97cfc9539bde3847c7f3c62db)
> gc: add foreign key ON DELETE CASCADES to uo_enrich table (#470)

- rpm/packagescanner.go
- rpm/packagescanner_test.go
A malicious tar archive with a member consisting of multiple "parent"
elements could cause a file outside of the target directory to be
overwritten.
Fixes: CVE-2021-3762
> rpm: prevent directory traversal when extracting

- rpm/packagescanner.go
- rpm/packagescanner_test.go
A malicious tar archive with a member consisting of multiple "parent"
elements could cause a file outside of the target directory to be
overwritten.
Fixes: CVE-2021-3762
Backports: #478
(cherry picked from commit 691f2023a1720a0579e688b69a2f4bfe1f4b7821)
> backport: rpm: prevent directory traversal when extracting

- crda/matcherfactory.go
- crda/normalizeseverity.go
- crda/remotematcher.go
- crda/remotematcher_test.go
- crda/testdata/pypi/flask/0.12.json
- crda/testdata/pypi/pyyaml/5.3.json
- libvuln/opts.go
- matchers/defaults/defaults.go
The default api in crda remote matcher will serve 100rpm
The other key which can be optained by making an api call will be able to serve 1800 rpm to start with . We are positive about
increasing it even more.
Our api will have proper 3scale limits in place and we have removed the scenario which resulted in our system downtime.
Continued from https://github.com/quay/claircore/pull/419
> crda: remote matcher with new crda api, source, and key

- pkg/cpe/attribute_string.go
- pkg/cpe/testdata/README.md
- pkg/cpe/wfn.go
- pkg/cpe/wfn_test.go
Adding a test that unbinds and rebinds the official CPE dictionary shook
out a bug.
> cpe: add dictionary test

- alpine/distributionscanner.go
- alpine/distributionscanner_test.go
- alpine/release.go
- alpine/updaterset.go
Implemented Alpine 3.15 similar to [alpine: add new releases 3.13 and 3.14](https://github.com/quay/claircore/pull/464)
Fixed indentation in [alpine/distributionscanner_test.go](https://github.com/quay/claircore/compare/main...xXPOLYGONXx:add_alpine_release_3.15?expand=1#diff-5fb50dfdf52a36fbee6aa96e54351867e53d17a8284dca7c84fa30862bfec15d)
> Add Release Alpine 3.15

- aws/client.go
- aws/updater.go
- debian/parser.go
- internal/xmlutil/charset.go
- internal/xmlutil/xmlutil.go
- oracle/parser.go
- photon/parser.go
- rhel/parser.go
- suse/parser.go
- ubuntu/parser.go
Debian recently added an `encoding` attribute to the XML text element in their OVAL feeds, which causes the stdlib xml decoder to call the `CharsetReader` member. We should populate this for robustness' sake.
> bug: xml decoding

- java/jar/jar.go
- java/jar/jar_test.go
- java/packagescanner.go
It's possible that badly formatted jars can escape detection
and zip.NewReader will report back an error. We can't really
advance from here so report error and return.
> java: account for zip reporting file with bad format

- rhel/repositoryscanner.go
- rhel/repositoryscanner_test.go
This change causes the repository scanner to fall back to the Container
API when a Dockerfile is present but missing expected labels, not just
when a Dockerfile is missing.
Closes: PROJQUAY-2868
> rhel: fix error on old containers

- crda/remotematcher.go
- libvuln/libvuln.go
This logs the name of each of the matchers that the matcher
instance will use. This info on startup helps when debugging
reports.
> libvuln: log the names of all the configured matchers

- ubuntu/updaterset.go
Without this the log would identify a failure but mis-report
the release as the tasks are performed in a goroutine and the
ctx wasn't recreated.
> ubuntu: updater log evaluation bug

- java/jar/jar_test.go
Recent internal changes caused this test to emit logs, which
(purposefully) panics if not set up correctly.
> jar: fix text harness

- internal/vulnstore/postgres/gc.go
- internal/vulnstore/postgres/gc_test.go
- libvuln/updates/manager.go
This change will delete the orphaned vulns, ie. those
that are no longer tied up the update_operations, in
one query rather than 3 seperate ones.
> GC: Do query execution all in one rather than separate

- libindex/opts.go
- libvuln/opts.go
These changes just allow a connection string to be empty, which currently has the database driver use the environment.
Enables quay/clair#1467.
> libindex, libvuln: allow empty connection string

- crda/matcherfactory.go
- crda/remotematcher.go
- crda/remotematcher_test.go
This patchset changes the `crda` defaults so that it's disabled without
a config providing an API key.
> crda: remove default key

- enricher/cvss/cvss.go
- enricher/cvss/cvss_test.go
Many of the CVEs that are looked up for enrichment are duplicates and therefore the DB work is duplicated. This PR adds a small map to cache the `EnrichmentRecord`s that have already been looked up from the DB.
> enrichment: Optimize the way enrichments are queried

- alpine/fetcher.go
- debian/sourcemapper.go
- debian/updater.go
- pkg/ovalutil/fetcher.go
- pyupio/updater.go
- rhel/updaterset.go
- ubuntu/updater.go
This makes all the uses of an `if-none-match` header also check the response's Etag. Some servers send weak validators with non-identity content encodings, and don't validate them when sent back. This prevents processing unchanged resources, but doesn't prevent all the network traffic.
Closes #559
> Check validator on 200 response

- crda/matcherfactory.go
- crda/remotematcher.go
The remote matcher is currently getting passed the client
used for all updating that includes more specific settings
for that workload (like ratelimiting API calls). This change
moves the CRDA matcher to use its own client with a specific
timeout that matches the context deadline.
> crda: Stop using the Client Clair instanciates

- ubuntu/releases.go
Currently the releaseToDist function returns discoDist
when it finds a Cosmic release. Correct that.
> ubuntu: update releaseToDist to correct cosmic error

- alpine/distributionscanner.go
- alpine/distributionscanner_test.go
- alpine/release.go
- alpine/testdata/3.16/etc/issue
- alpine/testdata/3.16/etc/os-release
- alpine/testdata/3.16/want
- alpine/updaterset.go
Alpine 3.16 will probably be released on 01.05.22 (https://gitlab.alpinelinux.org/alpine/aports/-/milestones/183#tab-issues). 
Preparing the project for being able to handle this version.
Implemented Alpine 3.16 similar to https://github.com/quay/claircore/pull/464 & https://github.com/quay/claircore/pull/524
> Add Release Alpine 3.16

- internal/matcher/match.go
vuln reports could be returned without vulns
Fixes #593
Error will be logged further up the stack, so removing log as well.
> matcher: fail vuln report on matcher error

- alpine/parser.go
- alpine/parser_test.go
- libvuln/migrations/07-force-alpine-update.sql
- libvuln/migrations/migrations.go
Alpine's security feeds list vulnerabilites by source
package and not binary package, hence we are currently
missing all the vulnerabilites where the binary package
is named differently from the source package.
> alpine: ingest alpine vulnerabilities as type SOURCE

- internal/vulnstore/postgres/enrichment.go
- internal/vulnstore/postgres/updatevulnerabilities.go
Signed-off-by: Iain Duncan <iain.duncan@uk.ibm.com>
This fixes #616 and has been tested in our local setup.
I wasn't sure if using the transaction was the right approach, if the `QueryRow` commands were moved above the `pool.Begin` commands then that would also fix the problem without having to put these commands in the transaction.
> postgres: run creates before creating transaction

- pkg/tarfs/tarfs.go
- pkg/tarfs/tarfs_test.go
If a caller passes an empty tarball, New now returns returns a
filesystem that will not error when walked. The alternative would be
to report an error from New, but changing it this way means callers do
not have to handle that explicitly.
> tarfs: always create a root directory

- rhel/rhcc/matcher_integration_test.go
- rhel/rhcc/parser_test.go
- rhel/rhcc/rhcc.go
- rhel/rhcc/updater.go
The updater in rhcc matcher was using CVE Name as the vulnerability name
which more closely aligns with vulnerabilities coming from unpatched
OVAL definitions. This change switchs rhcc matcher to use the advisory
name in the vulnerablity name field.
See-Also: #627
Here's a vulnerability generated with this patch:
```
{
"id": "5578",
"updater": "rhel-container-updater",
"name": "RHSA-2021:3665",
"description": "A directory traversal vulnerability was found in the ClairCore engine of Clair. An attacker can exploit this by supplying a crafted container image which, when scanned by Clair, allows for arbitrary file write on the filesystem, potentially allowing for remote code execution.",
"issued": "2021-09-28T00:00:00Z",
"links": "https://access.redhat.com/errata/RHSA-2021:3665 …
```
> rhcc: Update vulnerability details to match rhel patched

- crda/remotematcher.go
- crda/remotematcher_test.go
It is currently possible to modify the url after it's
assigned to the matcher struct i.e. when newMatcher is
called subsequently. This change ensures any url passed
to the constructor (via the option method) is cloned.
> crda: clone url when creating a new matcher

- dpkg/scanner_test.go
- dpkg/testdata/debian-only.status
I suspect this was fixed by switching to the textproto package, but this change
adds a test case to prevent a regression.
Closes: quay/claircore#297
> dpkg: test with known-problematic status file

- internal/vulnstore/postgres/recordupdatetime.go
This change makes sure all calls to modify the updater_status
table go through the transaction's connection instead of attempting
to acquire another one.
> updates: Use the tx's methods to record updater's status

- libindex/fetcher.go
- pkg/tarfs/parse.go
- pkg/tarfs/tarfs.go
- pkg/tarfs/tarfs_test.go
This change adds a dedicated error for when an invalid tarball is detected, and then adds a validation step to the fetcher.
> tarfs: format error

- libvuln/updates.go
This should all be done by the caller, but this seems to be an
oversight from moving that to the caller's responsibility.
> libvuln: don't attempt to decompress within OfflineImport

- toolkit/events/events.go
- toolkit/events/log.go
- toolkit/events/log_test.go
As a part of PROJQUAY-3147, this PR lays groundwork for having all the modular components emit event logs.
> Diagnostics groundwork

- .github/workflows/prepare-release.yml
As we now have nested submodules the Changelog
generator chokes on path prefixed versions. This
change exclude tags that don't start with `v`. Also
bump the tool version.
> chore: Add tag pattern to chg-log Changelog generator

- libindex/fetcher.go
Currently the error type gets lost in the stack, this
allows certain errors (particularly at the tarfs level) to
be surfaced to external callers of Index().
> fetcher: Wrap error to surface error type to external caller

- rhel/repositoryscanner.go
When the embedded build metadata indicates there are no content-sets associated with the container, fall through to the API call. This shouldn't happen, but does in some early RHEL 9 based containers.
> rhel: handle malformed build metadata

- go.mod
- go.sum
Allow the oval parsing to handle "unknown" dates coming in from Ubuntu.
> Chore: Bump goval-parser to v0.8.8

- .github/dependabot.yml
> cicd: enable dependabot for go modules

- java/jar/jar.go
We open META-INF dir in the jar file, this closes it.
> jar: Close META-INF

- test/periodic/rpm_test.go
A few constructed APIs started 404/403-ing. This change attempts to only use links returned by the API. This is all reverse-engineered, so I can only be so annoyed at having to do some additional reversing.
> periodic: attempt to follow API-created links

- rpm/ndb/package.go
- rpm/ndb/package_test.go
This should handle the case where the RPM DB has unpopulated slots. My previous reads of the RPM C code had me thinking that the DB was recompacted after transactions, but this seems to no be the case. This implements a sanity check that exists in the C slot reading code.
Closes: quay/clair#1645
> ndb: handle noncontiguous package slots

- pkg/tarfs/tarfs.go
- rpm/packagescanner_test.go
- rpm/testdata/layers/.gitignore
This fixes the `tarfs` code to use the full path where appropriate, instead of just the file name.
Closes #736
> tarfs: lookup path bug

- pkg/tarfs/tarfs.go
Hard linking to directories isn't _technically_ disallowed, but not a common occurrence. This change adds support for it.
Closes: #737
> tarfs: support traversing intermediate hard links

- aws/client.go
- crda/remotematcher_test.go
- debian/sourcemapper_test.go
- libvuln/jsonblob/jsonblob_test.go
- pkg/tmp/file.go
- rhel/fetch_test.go
- rhel/matcher_test.go
- rhel/rhcc/matcher_integration_test.go
- rpm/extract.go
- test/integration/engine.go
Used a script to fix up all the call sites:
git grep -l ioutil -- :/**.go |
while read f; do
for rule in \
'ioutil.Discard -> io.Discard'\
'ioutil.NopCloser -> io.NopCloser'\
'ioutil.ReadAll -> io.ReadAll'\
'ioutil.ReadFile -> os.ReadFile'\
'ioutil.TempDir -> os.MkdirTemp'\
'ioutil.TempFile -> os.CreateTemp'\
'ioutil.WriteFile -> os.WriteFile'\
; do
gofmt -w -r "$rule" "$f"
done
goimports -l -w "$f"
gofumpt -l -w "$f"
done
Running this on the previous commit should produce the same results.
> all: rewrite uses of `ioutil`

- rhel/repositoryscanner.go
- rhel/rhcc/scanner.go
Currently it is possible that if the repo2cpe_mapping_url or the repo2cpe_mapping_file (or indeed if the endpoint is down) that we will panic as the mappingFile will cast to a nil. This will check for a nil mapper before it gets accessed and error out.
> rhel: Check that after casting to mappingFile we have a usable mapper

- .github/workflows/main.yml
Only run CI on push if going to main, keep PR branches open in case we have a situation where we're merging into a non-main branch.
> chore: restrict CI

- gobin/exe.go
Currently the logs get spammed with
`unable to open executable error="not a Go executable"`, this reduces the level of these logs from Info to Debug.
> gobin: Reduce log level for non-go binaries

- datastore/postgres/layerscanned.go
- indexer/ecosystem.go
- indexer/layerscanner/layerscanner.go
- indexer/opts.go
- libindex/libindex.go
- libindex/options.go
This change removes the code that disables RPC scanners when airgap
is true allowing hybrid implementations to be configured with local
resources. It assumes that the client passed will be airgap aware.
TODO
> airgapped: Remove airgapped logic from the core in lieu of the client being passed being airgap aware

- gobin/coalescer.go
- gobin/ecosystem.go
The coalesce function requires each ecosystem to have a coalescer, this change add a vanilla one.
> gobin: Add noop Coalescer

- indexer/layerscanner/layerscanner.go
Currently we just log that there was an error and the layer object. This change removes the layer object and adds the error.
> logging: Expose error from SetLayerScanned in the logs

- java/packagescanner.go
> java: fix maven search metric

- pkg/tarfs/tarfs_test.go
Used this to help diagnose some layers. Just drop any tar into `testdata/known/$filename` and then run `go test -run Known/$filename`.
> tarfs: add simple walk test

- .github/workflows/release.yml
The switch to a `fetch-depth` of "0" means the `--tags` option errors out.
> chore: fix `git fetch` in release process

- gobin/exe.go
- gobin/gobin.go
This change reaches into the `debug/buildinfo` package to determine when the returned errors aren't worth reporting.
> gobin: reduce debug verbosity

- .github/workflows/golang-image.yml
- .github/workflows/main.yml
- etc/Dockerfile
Start building the 1.20 container -- this is needed to pick up a fix in the `debug/elf` package.
> chore: update go versions

- ubuntu/distributionscanner.go
Noticed these were defined but never used. Might as well use them :)
> ubuntu: use the preexisting global vars

- dpkg/distroless_scanner.go
- dpkg/distroless_scanner_test.go
- dpkg/ecosystem.go
This change adds a distroless scanner which is in itself a different flavour of dpkg scanner. It reads the dpkg files found in the var/lib/dpkg/status.d/ directory.
> dpkg: Add distroless scanner

- rhel/internal/common/updater.go
The Red Hat Product Security team tells us that these files won't update more than once a day. This changes the interval in the updater to 24 hours (the most common length of a day).
Closes: PROJQUAY-5069
> common: increase update interval

- aws/updater.go
- aws/updater_test.go
We are missing the epoch for the Amazon Linux vulnerability `FixedInVersion`. The `rpm` package scanner accounts for it, so it's possible we have been missing a bunch of Amazon Linux vulnerabilities.
> aws: include epoch in FixedInVersion

- rhel/matcher.go
`vulnVer` is overwritten no matter what, so there is no need to define it until necessary
> chore: remove unnecessary variable definition

- java/jar/jar.go
I feel like this looks cleaner than using `bytes`
> chore: use string instead of []byte in pom analysis

- dpkg/distroless_scanner.go
- dpkg/scanner.go
This change makes the dpkg indexer consider the `Status` field. This can be set a few different ways depending on if dpkg-managed files are left after a removal operation or not.
> dpkg: consider `Status` field

- pkg/ovalutil/rpm.go
- pkg/ovalutil/rpm_test.go
- rhel/parser.go
The 'none' type appears in "empty" OVAL v2 files (look for any 567 byte file like this one: https://access.redhat.com/security/data/oval/v2/RHEL8/openshift-service-mesh-2.3-including-unpatched.oval.xml.bz2).
We already ignore these because `def.Advisory.AffectedCPEList` is empty/`nil`, but this PR makes the code more defensive.
> chore: skip 'none' rhel vulnerability definition type

- alpine/fetcher.go
- aws/client.go
- debian/updater.go
- enricher/cvss/cvss.go
- rhel/rhcc/updater.go
- ubuntu/updater.go
The fact that this idiom was applied unevenly means the interface is in need of retooling, IMO.
See-also: PROJQUAY-5165
> all: audit `tmp.NewFile` use

- etc/extract-layers
This takes a skopeo-formatted source and some tar patterns and extracts the layers in order. For example:
etc/extract-layers docker://registry.access.redhat.com/ubi8/ubi:latest var/lib/dnf var/lib/rpm
> etc: add image debugging script

- pkg/pep440/range_test.go
- pkg/pep440/version_test.go
This came up in a chat, so I decided to add some tests to confirm ClairCore can handle this scenario. This popped up when determining if Clair can find https://github.com/certifi/python-certifi/security/advisories/GHSA-43fp-rhv2-5gv8 when the metadata says the version is `2022.12.7`. See https://github.com/pypa/setuptools/issues/302 and https://peps.python.org/pep-0440/ for more information about how `setuptools` removes leading zeroes and `pep440` specifies date-versions have leading zeroes removed.
> pep440: add leading zeroes tests

- indexer/opts.go
- libindex/options.go
At this point, these options are no longer used anywhere, so might as well remove them to ensure nobody uses them.
> chore: delete airgap options

- test/fetch/layer.go
I ran into this when I was testing out images pulled from quay.io. The returned `realm` for that was `https://quay.io/v2/auth`
> chore: do not assume challenge endpoint called token

- test/integration/engine.go
This should make things consistent and work across locales.
> integration: explicit locale in initdb(1)

- rpm/internal/rpm/header.go
- rpm/packagescanner.go
It seems like headers in bdb databases don't always have the same sorting applied to the tags. This change catches when a header region is less orderly and falls back to a lax verification mode.
Closes: #885
> rpm: handle bdb header weirdness

- docs/CONTRIBUTING.md
- docs/SUMMARY.md
Putting it at this path should take advantage of the GitHub UI and capture some contribution flow knowledge.
> docs: contributing guidelines

- libvuln/libvuln.go
- test/bisect/main.go
- test/bisect/main_test.go
This updates the bisect tool to actually work enough to make `go generate github.com/quay/claircore/datastore/postgres` work.
> bisect tool update

- .github/workflows/main.yml
This is an attempt to speed up CI, now that we don't have any external process dependencies.
> chore: use non-containerized postgres and go

- datastore/postgres/update_e2e_test.go
This was causing some tests to fail, seemingly because of the "+".
Also update some lints and best practices.
This is seemingly causing Clair's `ppc64le` tests to fail while logging.
> postgres: fix test names

- .github/workflows/main.yml
- go.sum
- toolkit/go.mod
- toolkit/go.sum
This should make the tests fail if the tests for any module fails and print the postgres logs in that case.
> cicd: fix test invocation, print postgres logs

- datastore/postgres/deletemanifests_test.go
- datastore/postgres/migrations/indexer/07-index-manifest_index.sql
- datastore/postgres/migrations/migrations.go
- test/integration/engine.go
By deleting a broad index for space reasons (
https://github.com/quay/claircore/commit/d9abe3db42bb533962ff163b3521587fc4b3f0cc) I inadvertantly slowed the delete manifests query due to a delete cascading to the manifest_index table and having to do a seq scan. This change adds a dedicated index for queries involving manifest_id.
> indexer: Add index to manifest_index table to aid deletions

- datastore/postgres/packagesbylayer.go
For all existing entries in the package_scanartifact table, filepath will be null. This is not an issue until one of the scanner versions is updated and the indexing process will attempt to reindex the layers with the new scanner and retrieve the existing packages from the package_scanartifact (ie. reconstruct the index_report). This change ensures null is handled.
> whiteout: Account for null filepath column

- java/matcher.go
- java/matcher_integration_test.go
- java/matcher_test.go
This is so other users of this library may use the matcher, as necessary.
> java: expose matcher

- datastore/postgres/querybuilder.go
- datastore/postgres/querybuilder_test.go
This view has always existed but never been used (AFAICT). Lately it has been problematic to query all of the vuln table as some vulnerabilities associated with older update_operations we're deleted or duplicated in new update_operations.
TODO
> matcher: Use latest_vuln view in lieu of querying vuln table

- alpine/parser.go
- alpine/parser_test.go
- libindex/libindex_test.go
https://cve.mitre.org is deprecated in favor of https://www.cve.org, so Alpine vulnerabilities should point to the new website.
> alpine: update vulnerability link

- crda/matcherfactory.go
- matchers/defaults/defaults.go
As we now have a native java matcher we should add it to the defaults, it will be doing similar work to the CRDA matcher so people will most likely want to disable the CRDA matcher (by removing its config). The CRDA matcher will be removed in later versions.
> java: Add java.Matcher to defaults

- datastore/postgres/migrations/matcher/09-delete-pyupio.sql
- datastore/postgres/migrations/migrations.go
Because no more update_operations are being created for pyupio the current vulns will not be GCed. This is a manual intervention to clear them up and avoid double reporting.
> python: Delete pyupio vulns

- gobin/gobin.go
- indexer/controller/coalesce.go
- indexer/layerscanner.go
- indexer/packagescanner.go
This has become an issue with more language support where the packages need to be associated to a repository but the repo scanner just ends up being a packagescanner-lite (repeating work). This change lets packageScanners implement an optional method to return a default Repository which will be created during indexing.
> indexer: Add ability for package scanner to return a default repository

- .github/workflows/main.yml
- test/integration/db.go
- test/integration/integration.go
This moves some checks to a catch-all "gating lints" job.
It also adds a caching scheme to not re-test commits.
> cicd: gating lints

- gobin/exe.go
- gobin/gobin.go
- gobin/matcher.go
- updater/osv/osv.go
In order to use the db for version filtering, the package created with the gobin package detector needs to add normalized versions. The detector also needs implement VersionFilter and VersionAuthoritative, then Vulnerable() becomes a no-op.
> gobin: Make matching use VersionFilter for db side filtering

- ruby/matcher.go
- ruby/matcher_integration_test.go
- ruby/matcher_test.go
- ruby/testdata/indexreport-bullseye-ruby.json
- updater/osv/osv.go
Note: Ruby recommends semver, but it is not enforced. I am taking the stance here that we will not support non-semver versions. This is relevant because I did find an example which broke semver: https://osv.dev/vulnerability/GHSA-23f7-99jx-m54r (0.119.0.beta1 is not proper semver. It should be 0.119.0-beta1)
> ruby: add vuln matching

- datastore/postgres/migrations/matcher/10-delete-osv.sql
- datastore/postgres/migrations/migrations.go
- java/matcher_integration_test.go
- python/matcher_integration_test.go
- ruby/matcher_integration_test.go
- updater/osv/osv.go
- updater/osv/osv_test.go
Having one generic updater has issues when not all ecosystems have
updates. The osv updater will associate the new vulns from the updated
ecosystem with a new osv update_operation and the unchanged vulns will
be associated to an old update_operation. This throws up 3 potential
issues: 1) as we now use the latest_vuln view only the vulns from the
updated ecosytems are available to query 2) The GC can potentially
delete those un-updated vulns 3) when the notification system tries to
calculate the delta between previous and current update_operations it
will receive unexpected results. This pushes the updater creation to
the osv.factory which creates an updater per ecosystem (i.e. osv/go).
The fetching/parsing logic remains largely unchanged.
> osv: Split osv updater into updaterset and updater

- .github/dependabot.yml
Also tweaks the commit format a little bit to fit the style of human-authored commits in the repo.
> chore: make dependabot harass a specific team

- .github/workflows/updater-check.yml
- java/matcher_integration_test.go
- python/matcher_integration_test.go
- ruby/matcher_integration_test.go
- test/periodic/updater_test.go
- updater/defaults/defaults.go
- updater/osv/osv.go
- updater/osv/osv_test.go
This corrects an oversight when the change to splitting out ecosystems was done: the factory requires a `Configure` call, which is unsafe to do on a global variable. This was causing the `updater-check` CI to fail. With the change, this is no longer the case:
> osv: remove package-level Factory instance

- datastore/postgres/enrichment.go
- datastore/postgres/get.go
- datastore/postgres/migrations/matcher/11-add-update_operation-mv.sql
- datastore/postgres/migrations/migrations.go
- datastore/postgres/querybuilder.go
- datastore/postgres/updatevulnerabilities.go
Querying the update_operations table for the latest operations creates a lot of CPU load on the DB. When the data is pulled into a materialized view we can take the CPU hit when the update_operation is being created as opposed to every time we receive a vulnerability report request.
> matcher: Use materialized view to speed up queries to update_operations

- libindex/libindex.go
I believe the new layerscanner construction work regressed this resolver being added to the indexer options.
> whiteout: Add back whiteout resolver

- python/matcher.go
- python/matcher_test.go
Currently we are assuming all python OSV url-encoded version strings have a fixed in version, but it appears like if a fixed version is not included the package is still vulnerable. We need to account for this behaviour.
Example warning:
```
WRN missing upper version component=internal/matcher/Controller.Match fixed in version=introduced=2.2.0&lastAffected=3.0.1 matcher=python package=pypdf2 request_id=999390f4cd1c7a56
```
> Python: Account for fixed_in information that has no fixed version

- java/jar/jar.go
This gets real chatty in a loaded production deployment.
> jar: don't info-log every properties file

- gobin/gobin_test.go
Unit test `TestScanner` builds and scans a layer containing a go executable. Clair doesn't recognise eg. Mac ARM64 go executables, so this test fails when run on an ARM Mac.
Fix: always (cross-)compile a Linux AMD64 executable, regardless of the host platform.
Alternatively it's simple to get gobin's `Detector.Scan(...)` to recognise the Mac ARM64 Mach-O executable header, but I don't whether other changes would be needed to fully support Mac ARM go binaries in Clair.
> gobin: fix unit test when run on ARM64

- rhel/parse_test.go
- rhel/parser.go
- rhel/rhel.go
- rhel/testdata/rhel-8-rpm-unpatched.xml
There is condition that excludes cve definition types when converting
OVAL definitions to vulns, currently for rhel8 unpatched feeds
the definitions are either oval:com.redhat.cve:def:... or
oval:com.redhat.unaffected:def:...
> rhel: Include cve defs when parsing through rhel oval feeds

- datastore/postgres/connect.go
This had already been removed but when the code was restructured it was accidentally added back. This hopefully removes it once and for all.
> postgres: remove hardcoded MaxConns config parameter

- datastore/postgres/enrichment.go
- datastore/postgres/migrations/matcher/12-add-latest_update_operation-index.sql
- datastore/postgres/migrations/migrations.go
- datastore/postgres/updatevulnerabilities.go
Without concurrency we are seeing heavy locking on the production DB. This option will mean data is slightly latent but will not lock the materialized view for reading.
> datastore: refresh materialized view concurrently

- rhel/fetch_test.go
- rhel/matcher_test.go
- rhel/parse_test.go
- rhel/rhel.go
- rhel/updaterset.go
- test/ovaldebug/main.go
This needs to be configurable at the factory level instead of the updater level as the user is unlikely to know the rhel updater names nor should they have to.
> rhel: correct config location for ignoring unpatched vulns

- python/matcher.go
- python/matcher_test.go
We weren't (I wasn't) accounting for the valid scenario when the vulnerability was open-ended defined by the "introduced" key and the absence of any other valid keys.
> python: account for just introduced key in OSV data

- .github/codecov.yaml
- .github/workflows/main.yml
I _think_ this is the reason that commits are not getting associated with the `main` branch when merged.
> cicd: specify branch in codecov arguments

- go.mod
- go.sum
The `toolkit` module needs to be versioned properly so that consumers are using the correct version.
> claircore: fix toolkit versioning

- indexer/controller/controller.go
- indexer/controller/controller_test.go
- indexer/controller/state.go
In the indexer controller's state machine, inside `run()`, errors from `SetIndexReport()` were logged but otherwise unhandled. 
If an error occurred, a correct index report could be returned in the HTTP response, but an incomplete one from a previous state would exist in the database.
> Indexer: handle SetIndexReport() errors

- datastore/postgres/registerscanners.go
1 second was too short to initialise with a remote Postgres, when running under the debugger in VSCode
> datastore: remove arbitrary register scanner 1sec timeouts

- debian/distributionscanner.go
- debian/distributionscanner_test.go
- debian/testdata/distroless_dist/10/etc/os-release
- debian/testdata/distroless_dist/11/etc/os-release
- debian/testdata/distroless_dist/9/etc/os-release
- osrelease/scanner_test.go
- osrelease/testdata/distroless_corrupt_layer
- osrelease/testdata/distroless_valid_layer
Linked issue: https://github.com/quay/claircore/issues/1018
This PR aims to introduce support for distroless /etc/os-release file parsing in order to allow for vulnerability matching. Further details can be found in the linked issue.
This PR contains:
- Test files of example /etc/os-release files for distroless images
- An update to the distributionscanner_test.go which adds "test cases" for the dist and distroless_dist file paths containing test data.
- Use of a regex pattern to get the version name from the VERSION field wrapped in brackets, which is then unpicked as before.
> debian:distroless dist parsing support and tests

- java/jar/jar.go
- java/jar/jar_test.go
- java/jar/testdata/malformed_zip.MF
Some types of jar file corruption don't cause errors as soon as the file is opened with `archive/zip`, but only later when the scanner looks for specific zip entries. Currently the error causes the indexing to fail completely.
So: Log and skip any jar files where `archive/zip` errors with "not a zip file"
---
Example of a weirdly corrupt jar: 
https://github.com/IBM/db2-samples/blob/master/repl/xmlpubtk/loadqueue/LoadQueue.jar
```
/tmp/LoadQueue.jar: Java archive data (JAR)
```
```
java.util.zip.ZipException: invalid END header (bad central directory offset)
at java.util.zip.ZipFile.open(Native Method)
at java.util.zip.ZipFile.<init>(ZipFile.java:247)
at java.util.zip.ZipFile.<init>(ZipFile.java:172)
at java.util.zip.ZipFile.<init>(ZipFile.java:143)
at …
```
> jar: skip corrupt jar files

- .github/workflows/main.yml
- toolkit/events/events.go
- updater/updater.go
This updates CI to only run on supported versions of go and allow us to use some 1.20 niceties, notably `errors.Join`.
> cicd: update go version

- .github/workflows/update-clair.yml
Something we have to do over and over is update clair with the latest claircore tag. This automates some of that workflow.
TODO:
> ci: create clair PR when new claircore tag is created

- java/jar/errors.go
- java/jar/jar.go
- java/jar/jar_test.go
- java/packagescanner.go
This should provide for more accurate details on where packages are discovered, especially when recursing into embedded jars.
Closes: #1065
> jar: improve recursive path tracking

- gobin/exe.go
- gobin/gobin.go
- gobin/gobin_test.go
This replaces the "runtime" package with its proper name, and documents and extends the main module handling.
See-also: PROJQUAY-5912
> gobin: improve handling of go versions

- .github/scripts/prepare-release
Certain PRs are worthy of changelog entries and are tagged with the label `needs-changelog`, when it comes to release time we should make sure all merged PRs no longer have the label.
> chore: return if merged PRs exist with needs-changelog label

- alpine/ecosystem.go
- apk/scanner.go
- apk/scanner_test.go
Refs: https://github.com/quay/claircore/issues/923
> feat: split `apk` out of `alpine`

- .github/workflows/updater-check-failures.yml
- .github/workflows/updater-check.yml
- aws/client.go
- aws/internal/alas/repomd.go
- aws/internal/alas/repomd_test.go
- aws/internal/alas/testdata/test_repomd.xml
- aws/internal/alas/updates.go
- aws/internal/alas/updates_test.go
- aws/matcher_test.go
- aws/updater.go
- aws/updater_test.go
- go.mod
- go.sum
See the [Period Check](https://github.com/quay/claircore/actions/runs/6376455252/job/17303489814) failure for the inciting incident.
This adds an additional CI action to create issues when that job fails, pulls the `alas` dependency internally (~~I thought I was going to have to fix this in there~~ Ended up doing that, it was less odd.), then adds the both-ways date parsing.
```
% go test -v -run AWS -enable
=== RUN   TestAWS
=== RUN   TestAWS/aws-AL1-updater
testing.go:98: {"level":"debug","release":"AL1","component":"aws/Client.getMirrors","zlog.testname":"TestAWS/aws-AL1-updater","caller":"client.go:219","message":"successfully got list of mirrors"}
testing.go:98: {"level":"debug","zlog.testname":"TestAWS/aws-AL1-updater","component":"aws/Client.RepoMD","mirror":"http://packages.us-west …
```
> aws: date format

- .github/workflows/changelog-label.yml
This is a github action to automatically remove the `needs-changelog` label.
All the parts have been tested piecewise, but this may require some followups when actually running in the runner environment.
> cicd: add cronjob to help with the `needs-changelog` label

- .github/workflows/changelog-label.yml
See https://github.com/quay/claircore/actions/runs/6461233069/job/17540497306
It knows it's in an Actions environment, but not enough to just load the token off disk.
> cicd: pass GitHub token in workflow

- rpm/packagescanner_test.go
A typo in 26539f2e9e resulted in `TestScan/NodeJS` failing.
This wasn't caught in local testing or in the normal CI due to our caching scheme.
> rpm: fix repo name in test harness

- .github/workflows/main.yml
- .github/workflows/release.yml
- .github/workflows/update.yml
I noticed the gh-pages docs aren't rendering correctly. I think this should fix it, but at the very least should make it behave more like my development environment.
> cicd: use latest mdBook

- .github/codecov.yaml
I find the "patch" stats failing CI to be very annoying. Refactors that net positive in coverage can still get hit by it. This change still has it reported, but it won't fail the CI.
> cicd: tweak per-patch codecov reporting

- indexer/controller/coalesce.go
- indexer/layerscanner.go
- internal/matcher/controller.go
- internal/matcher/doc.go
- internal/matcher/match.go
- libindex/libindex.go
- libindex/libindex_test.go
While looking around in the code for `errors.Join` reimplementations, I noticed some other odd error-handling patterns, mostly around `errgroup`.
There's currently two `errgroup`+`semaphore` usages that I didn't touch: `libvuln/updates` and `datastore/postgres`. In both cases they're using the same pattern, and in both cases they're due to have more drastic changes than refactoring the internal concurrency.
> chore: audit `errgroup` usage

- rhel/matcher_test.go
- rhel/rhcc/updater.go
- test/integration/poison_http.go
This should help us root out inappropriate uses of the default `net/http` resources.
> integration: poison default http resources

- updater/osv/osv.go
We mention https://ossf.github.io/osv-schema and the values there are (mostly) capitalized. As we lower the ecosystems we get from ecosystems.txt we should lower the config values too or they won't match (or we need to direct users to lower-case any ecosystems they add).
> osv: lower allowlist config values for osv ecosystems

- alpine/distributionscanner.go
- apk/scanner.go
- debian/distributionscanner.go
- dpkg/distroless_scanner.go
- dpkg/scanner.go
- gobin/gobin.go
- java/packagescanner.go
- java/reposcanner.go
- osrelease/scanner.go
- python/packagescanner.go
- python/reposcanner.go
- rhel/distributionscanner.go
- rhel/repositoryscanner.go
- rhel/rhcc/scanner.go
- rpm/packagescanner.go
- ruby/packagescanner.go
- ruby/reposcanner.go
- scanner/pkgconfig/scanner.go
- ubuntu/distributionscanner.go
- whiteout/scanner.go
Doing this should allow us to realize potential memory savings enabled by #1061.
All the in-tree Scanner implementations should now share a single `tarfs.FS` instance per layer.
> all: use `Layer.FS` method

- oracle/parser.go
Realized I never followed up https://github.com/quay/claircore/pull/956.
This is required, as we never recognized Oracle Linux 9 as a valid platform when reading the OVAL file
> oracle: support oracle linux 9 vulnerabilities

- updater/driver/go.sum
This kept updating locally, so I decided to just upstream this. I think this started with https://github.com/quay/claircore/pull/1107
> chore(deps): update updater go.sum

- indexer/layerscanner.go
This is a frustration in environments where we can see an error surfacing but it's difficult to tie it to a specific layer for debugging purposes.
> layerscanner: add layer hash to error context

- aws/updater.go
- datastore/postgres/gc_test.go
- java/jar/jar_test.go
- libvuln/libvuln.go
- libvuln/options.go
- oracle/updater.go
- oracle/updater_test.go
- photon/photon.go
- suse/suse.go
- test/fetch/layer.go
- test/fetcher.go
- test/integration/engine.go
- test/integration/poison_http.go
- test/integration/poison_http_test.go
- test/layer.go
- test/packagescanner.go
- test/periodic/periodic_test.go
- test/periodic/rpm_test.go
Almost all of these uses were introduced to make the ergonomics nicer, but they work against being explicit about network traffic.
This is a pass attempting to root out all the uses of the `http.DefaultClient`.
There's effectively 2 OK uses of the `http.Default*` variables:
- When not in an integration test (or in a cached-tools database test), as an assert the test will not talk to the network as configured.
- When in a test, after `integration.Skip` has been called.
Packages in the `test/` hierarchy should basically never use `DefaultClient`/`DefaultTransport`, as they have trickier logic to try to do as much as possible even if not in an integration test.
> all: purge `http.DefaultClient`

- pkg/tarfs/parse.go
If the value is being loaded this way, it should only be up to 11 digits long and thus impossible to overflow an int64, but doing this way "proves" that.
> tarfs: check a potential interger overflow

- libindex/fetcher.go
- libindex/tempfile_linux.go
- libindex/tempfile_unix.go
- libindex/tempfile_windows.go
`O_TMPFILE` does not exist on non-linux unix-based OSes, so I was unable to build ClairCore on my macOS (Darwin) machine. Similarly, I don't think it exists on Windows, but `FILE_FLAG_DELETE_ON_CLOSE` does, which sounds to be about the same.
The implemented solution for Darwin runs into the issue `O_TMPFILE` aimed to fix: ClairCore crashing can still leave files on the system. Since this was previous behavior, I don't see this as a regression, necessarily.
> fix(libindex): temp files on non-linux

- libvuln/jsonblob/diskbuf_linux.go
- libvuln/jsonblob/diskbuf_unix.go
- libvuln/jsonblob/diskbuf_windows.go
- libvuln/jsonblob/jsonblob.go
- libvuln/jsonblob/jsonblob_test.go
This eagerly encodes Vulnerabilities and EnrichmentRecords to JSON and writes them to a disk-backed buffer. This should reduce memory consumption as long as the system actually allows for flushing disk cache.
See-also: PROJQUAY-5915
> jsonblob: add a disk buffering step

- ruby/matcher.go
- ruby/matcher_test.go
- ruby/version.go
- ruby/version_test.go
Implemented Ruby versioning based on https://github.com/rubygems/rubygems/blob/1a1948424aca90013b37cb8a78f5d1d5576023f1/lib/rubygems/version.rb
> fix(ruby): use more accurate versioning

- dpkg/scanner_test.go
- layer.go
- libindex/fetcher.go
- python/packagescanner_test.go
- rhel/repositoryscanner_test.go
- rpm/packagescanner_test.go
- test/fetcher.go
@RTann reported some unexpected memory usage, which led to figuring out that this finalizer doesn't work as intended.
This fixes the finalizer, then fixes the issues reported by the subsequent panics.
> claircore: fix `Layer` finalizer

- datastore/postgres/getupdateoperations.go
All users of this function expect the returned map to be non-nil when the returned error is non-nil. Returning `nil, nil` causes a panic in `libvuln.OfflineImport`: https://github.com/quay/claircore/blob/v1.5.20/libvuln/updates.go#L40
There is already another line above this (line 230) which returns `out, nil` when `errors.Is(err, pgx.ErrNoRows)`. I guess the one that returned `nil, nil` was a mistake?
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x28b53dd]
goroutine 1 [running]:
github.com/quay/claircore/libvuln.OfflineImport({0x34f75e0?, 0xc0008782d0?}, 0xc00100b0e0, {0x34c55e0?, 0xc00048d000})
github.com/quay/claircore@v1.5.21-0.20231211033403-8fd9a12427a0/libvuln/updates.go:40 +0x25d …
```
> postgres: return empty map instead of nil

- datastore/postgres/affectedmanifest.go
- datastore/postgres/distributionsbylayer.go
- datastore/postgres/get.go
- datastore/postgres/indexdistributions.go
- datastore/postgres/indexer_store.go
- datastore/postgres/indexmanifest.go
- datastore/postgres/indexpackage.go
- datastore/postgres/indexreport.go
- datastore/postgres/indexrepository.go
- datastore/postgres/layerscanned.go
- datastore/postgres/manifestscanned.go
- datastore/postgres/packagesbylayer.go
- datastore/postgres/persistmanifest.go
- datastore/postgres/repositoriesbylayer.go
- datastore/postgres/setindexfinished.go
- datastore/postgres/setindexreport.go
- datastore/postgres/setlayerscanned.go
This removes all the internal timeouts for this package. The idea was to keep execution time bounded, but it's becoming increasingly clear this is just a source of problems.
> postgres: remove internal timeouts

- java/jar/jar.go
- java/packagescanner.go
Avoids reallocations when buffers grow repeatedly for large files, and oversizing (as buffer capacity doubles when capacity is reached).
When indexing an unusually large image we've seen, that has deeply nested jars, this reduces peak process size from 18.9Gb to 11.1Gb.
---
The jar spec says nested jars must be "stored" (not compressed) in the outer jar, so in principal the parsing of nested jars could re-use sections of the outer file's buffer, greatly reducing memory use ... but those changes would be much more intrusive so I don't know if you'd want to go that way.
> java: grow buffers to the right capacity before use

- libvuln/jsonblob/jsonblob.go
- libvuln/jsonblob/jsonblob_test.go
- libvuln/updates.go
- test/enrichment.go
A patch to fix the following BUG:
https://github.com/quay/claircore/blob/faffb8e880263171ca9b54dc2f5609547e53cbb7/libvuln/jsonblob/jsonblob.go#L94-L96
> enrichers: Load enrichments from jsonblob storage

- nodejs/coalescer.go
- nodejs/coalescer_test.go
- nodejs/ecosystem.go
- nodejs/packagescanner.go
- nodejs/packagescanner_test.go
- nodejs/testdata/README.md
Adds support for analyzing NodeJS packages in the form of npm package.json.
Note: This does not currently account for the package.json files being installed due to an rpm. In that case, the package.json file should **not** be scanned.
> nodejs: add package.json support

- rhel/ecosystem.go
- rhel/matcher.go
- rhel/updaterset.go
- rpm/bdb/bdb.go
- rpm/ecosystem.go
- rpm/internal/rpm/header.go
- rpm/native_db.go
- rpm/ndb/ndb.go
- rpm/packagescanner.go
Found these commits hanging out on #869, but they're pretty independent.
> rpm et. al.: lints

- rhel/distributionscanner.go
- rhel/distributionscanner_test.go
- rhel/testdata/releasefiles/atomichost-7/etc/os-release
- rhel/testdata/releasefiles/atomichost-7/etc/redhat-release
- rhel/testdata/releasefiles/atomichost-7/usr/lib/os-release
- rhel/testdata/releasefiles/atomichost-7/usr/lib/redhat-release
Without the updated regex, ClairCore did correctly detect `rhel:7` for this scenario, but it seemed more due to luck from thei line in the `os-release`: `REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"`
This change make the support explicit
> rhel: explicit RHEL Atomic Host support

- java/matcher.go
- java/matcher_test.go
- python/matcher.go
- ruby/matcher.go
- ruby/matcher_test.go
GHSA-qw4h-3xjj-84cc showed that `fixed` and `last_affected` are not required. See https://ossf.github.io/osv-schema/#requirements and https://ossf.github.io/osv-schema/#unfixed-vulnerability-example to see it is valid for neither one to exist in an entry.
This change accounts for this and updates the 'vulnerable' algorithm as follows:
1. Parse the `IndexRecord`'s version. If we cannot parse this, we cannot correctly know if it's vulnerable to anything
2. Compare the `IndexRecord` to the `introduced` version, if it exists
3. Compare the `IndexRecord` to the `fixed` version, if it exists
4. Compare the `IndexRecord` to the `last_affected` version, if it exists
5. Default to claim the package is vulnerable. This may introduce false positives/noise, but this may be unlikely enough to be ok so …
> fix OSV matching algorithms

- datastore/postgres/deletemanifests.go
- datastore/postgres/deletemanifests_test.go
- datastore/postgres/migrations/indexer/08-index-manifest_layer.sql
Update the delete logic to try and follow the existing indexes. This splits the functionality into 4 calls, get manifest ID, get layer IDs, delete manifest, delete layers.
> datastore: refactor deleteManifests to deal with large datasets

- datastore/postgres/updatevulnerabilities.go
- datastore/postgres/updatevulnerabilities_test.go
- datastore/updater.go
- libvuln/driver/updater.go
- libvuln/jsonblob/jsonblob.go
- libvuln/updates/manager.go
- libvuln/updates/manager_test.go
> updater: Support delta updates

- internal/zreader/zreader.go
- internal/zreader/zreader_test.go
- rhel/repositoryscanner.go
- rhel/rhcc/scanner.go
This should allow the data to fit in a k8s ConfigMap, for at least a little while longer.
```
% for z in bzip2 gzip zstd; do command $z -k *.json; done
% du -sh *.json*
100K    container-name-repos-map.json
12K     container-name-repos-map.json.bz2
16K     container-name-repos-map.json.gz
16K     container-name-repos-map.json.zst
2.0M    repository-to-cpe.json
60K     repository-to-cpe.json.bz2
96K     repository-to-cpe.json.gz
108K    repository-to-cpe.json.zst
```
> rhel, rhcc: add transparent decompression of sideband data

- rhel/internal/common/updater.go
I was testing something and saw the following:
```
{"level":"error","host":"scanner-v4-indexer-69c646f78f-n9fvh","component":"rhel/internal/common/Updater.Get","error":"received status code 'ƥ' querying mapping url","time":"2024-01-20T22:51:22Z","message":"error updating mapping file"}
```
I think it'd be more useful to see the number rather than the decoded value.
Also, I noticed a usage of `%v` with `fmt.Errorf`, and I believe `%w` is preferred, so I included that, too
> rhel-updater: improve error messages

- internal/zreader/compression_string.go
- internal/zreader/zreader.go
- internal/zreader/zreader_test.go
Noticed on #1213 that the zreader test was failing. I was able to reproduce reliably by just upping the number of test runs.
Ultimately, the zlib header is just 2 bytes and not sufficiently unique enough to get the autodetection to work. Currently we don't consume anything that's "bare" zlib (outside of HTTP requests, which are handled by `net/http` transparently), so I think it's fine to just drop it.
We never hit a problem in the fetcher because gzip and uncompressed tars have a sufficiently different header from the zlib header that it doesn't trip.
> zreader: remove zlib support

- nodejs/matcher_integration_test.go
- updater/osv/osv.go
For example, when looking at Go vulnerabilities, ClairCore does not specify any vulnerabilities are fixed. Only affected or not, essentially. This change includes `FixedByVersion`, when available.
> osv: set FixedInVersion for SEMVER ecosystems

- libvuln/updates.go
We have our own enricher running, and I got scared when I saw this log:
```
{"level":"info","host":"scanner-v4-matcher-dcff5f5cf-bl77v","component":"libvuln/OfflineImporter","updater":"nvd","ref":"5810c28c-e902-4529-b0a2-f7108ac78cf0","count":0,"time":"2024-02-01T17:44:46Z","message":"update imported"}
```
I realized this is just the vuln count and not the enrichment count, hence this PR
> libvuln: log offline enrichment count

- test/integration/embedded.go
Previous fix for the races messed with the logic such that integration tests weren't being run opportunistically. This should restore the correct behavior.
> integration: fix cached behavior

- alpine/matcher.go
I think we should check for "" and "0" before attempting to convert the version. No point if it's just "" or "0"
> alpine: reorder vulnerable checks

- rhel/repositoryscanner.go
- rhel/repositoryscanner_test.go
There's logic in the RHEL repository scanner to disable reaching out to the internet, but we currently set a default API endpoint during Configure to prevent that condition. These changes introduce a DisableAPI flag to allow the deactivation of the fetching from the Red Hat Container API.
> rhel: allow deactivation of ContainerAPI fetching

- gobin/exe.go
- gobin/exe_test.go
Some gobin versions are nanosecond timestamps and cannot be converted to a semver using the library. This change brings the semver parsing in-house and truncates any version segments to ensure they'll fit in int32s.
> gobin: parse semver and ensure segments fit in claircore.Version

- test/periodic/rpm_test.go
Using `eol_date` seems to work better than trying to filter on `release_categories`. Solr searching on lists seems to not work right.
Closes: #1249
> periodic: tweak search pattern

- rpm/ndb/package.go
- rpm/ndb/package_test.go
We error on some ndb files due to reading too many bytes and bleeding into the blob data (BlbS). This change bounds the data read to num slots * slots per page.
> ndb: bound slots data read to avoid over-reading

- gobin/exe.go
- gobin/exe_test.go
This error gets surfaced when the version is in the form 1.18. We see this in production due to the runtime version being sometimes reported as go1.18 (`go` is trimmed before the version conversion). Addition error context added for easier debugging.
> gobin: allow for empty version segment strings

- gobin/exe_test.go
Just adding this here so it's clear how ClairCore handles this case
> gobin: test +incompatible version

- rpm/bdb/bdb.go
We see DBs in the wild whose offset pages evidently report the expected length of the item incorrectly. No longer returning the error allows these incorrectly formatted DB files to be read at the expense of correctness.
> rpm: replace error with log when HOFFPAGE length is incorrect

- .github/workflows/changelog-label.yml
Adding the -r command to xargs (--no-run-if-empty) to avoid the command failing if the gh command does not yield results.
> chore: don't fail changelog label checker when there's no data

- .github/scripts/get-latest-golang-minor-version.sh
- .github/workflows/golang-image.yml
- .github/workflows/main.yml
- .github/workflows/updater-check.yml
- go.mod
- go.sum
- toolkit/go.mod
- updater/driver/go.mod
This adds go1.22 to the CI matrix, then updates the `go.mod` files to use go1.21.
> chore: add go1.22 to CI, update to go1.21

- docs/SUMMARY.md
- docs/contributor/commit-style.md
More contributors are coming directly to claircore, this adds the commit style guide from Clair (with the changelog generation references removed) to claircore so we have something to point to when new contributors' PRs fail the gating lints.
> docs: add commit style guide from clair

- updater/osv/osv.go
- updater/osv/osv_test.go
Occasionally there are OSV advisories that don't include any severity information in the `.severity` object but they do contain a severity in the `.database_specific` object. This change attempts to parse that severity if we don't get a severity from the native `.severity` object.
> osv: parse database_specific severity when no CVSS severity is defined

- test/integration/db.go
- test/integration/embedded.go
- test/integration/github_actions.go
- test/integration/integration.go
Here's what I did for testing this:
- Create a pod with a database in it.
<details>
```
% podman pod create claircore-integration-test
% podman create \
--pod claircore-integration-test \
--env POSTGRES_DB=clair \
--env POSTGRES_INITDB_ARGS=--no-sync \
--env POSTGRES_PASSWORD=password \
--env POSTGRES_USER=clair \
--health-cmd "pg_isready -U clair" \
--health-interval 10s \
--health-timeout 5s \
--health-retries 5 \
docker.io/library/postgres:15
% podman pod start claircore-integration-test
```
</details>
- Test external, build tag
<details>
```
% podman run --rm --pod claircore-integration-test \
--security-opt label=disable \
--mount "type=tmpfs,dst=/var/tmp" \
--mount "type=tmpfs,dst=/tmp" \
--mount "type=bind,src=$(go env GOMODCACHE),dst=/go/pkg/mod" \
--mount "type=bind,src=$(go env …
```
> cicd: db harness inside docker containers

- test/integration/embedded.go
- test/integration/fixup_linux.go
- test/integration/fixup_other.go
This is an embarrassing one that I should have thought through. Now, nothing should be panicking from the package block or an init function.
> integration: fix panic on platforms without embedded DB support

- pkg/tarfs/tarfs.go
- pkg/tarfs/tarfs_test.go
In `ReadFile`, we either follow symlinks or attempt to read the amount of data from the tar as specified by the `Size` field in `tar.Header`. When we come across a hardlink, however, we essentially tell the caller that the file is empty since the `Size` is `0`.
These changes to `ReadFile` are largely based on the changes @hdonnay made to `Open` for handling hardlinks: https://github.com/quay/claircore/commit/48317f8b4266d1e0f1478bcadef470d9865c61c2
> fix(tarfs): follow hardlinks in  `ReadFile`

- toolkit/types/cpe/match.go
- toolkit/types/cpe/match_test.go
- toolkit/types/cpe/relation_string.go
- toolkit/types/cpe/wfn.go
@crozzy discovered that the matching implementation behaved differently depending on whether the incoming CPE was unbound from a 2.2 URI or a 2.3 formatted string.
> cpe: fix cross-version matching

- datastore/enrichment.go
- datastore/matcher_store.go
- datastore/postgres/enrichment.go
- datastore/postgres/updatevulnerabilities.go
- datastore/updater.go
- libvuln/jsonblob/jsonblob.go
Add iterator-based vulnerability/enrichment writes to the existing DB APIs.
> datastore: Add vuln & enrich stream updates

- toolkit/types/cvss/cvss.go
- toolkit/types/cvss/cvss_v2.go
- toolkit/types/cvss/cvss_v2_score.go
- toolkit/types/cvss/cvss_v2_test.go
- toolkit/types/cvss/cvss_v3.go
- toolkit/types/cvss/cvss_v3_score.go
- toolkit/types/cvss/cvss_v3_test.go
- toolkit/types/cvss/cvss_v4.go
- toolkit/types/cvss/cvss_v4_score.go
- toolkit/types/cvss/cvss_v4_test.go
Fixes for #1230.
Thanks @pandatix for the concise bug report!
> cvss: bug fixes

- rpm/native_db_test.go
SQLite attempts to open WAL files alongside the database, which is a problem when running the tests out of a module download.
> rpm: add copy to SQLite test

- indexer/layerscanner.go
Persisting a layer as "scanned" happens in a separate transaction, and may fail. Do it after successfully persisting the scan results.
Avoids the fault where:
1. persisting the layer as scanned succeeds
ie. `ls.store.SetLayerScanned(...)` returns no error
1. persisting scan results fails
ie. `result.Store(...)` returns an error
1. a HTTP500 failed index report is returned
1. future index reports for the same manifest have no effect: the layer is marked as "scanned", so nothing is done
1. future vuln reports may be wrong: eg. if the failed scanner was a distribution scanner, the report is missing a distribution, and no vulnerabilities can be matched
> indexer: persist layer scanned after persisting scan results

- pkg/poolstats/collector.go
Fixes https://github.com/quay/claircore/issues/1326
Support publishing pxgpool stats from two different pools as Prometheus metrics with different `application_name` labels.
A clair running in `combo` mode after:
```sh
$ curl -s localhost:6061/metrics | grep pgxpool
pgxpool_acquire_count{application_name="libindex"} 22
pgxpool_acquire_count{application_name="libvuln"} 2
pgxpool_acquire_duration_seconds_total{application_name="libindex"} 0.044675038
pgxpool_acquire_duration_seconds_total{application_name="libvuln"} 0.0325225
pgxpool_acquired_conns{application_name="libindex"} 1
pgxpool_acquired_conns{application_name="libvuln"} 1
pgxpool_canceled_acquire_count{application_name="libindex"} 0
pgxpool_canceled_acquire_count{application_name="libvuln"} 0 …
```
> poolstats: support pgxpool metrics from two pools

- toolkit/types/csaf/csaf.go
- toolkit/types/csaf/csaf_test.go
- toolkit/types/csaf/testdata/cve-1999-0001-deleted.json
Adding the status field to be able to reason with whether the advisory has been deleted.
> csaf: add status to the document.tracking

- pkg/tarfs/file.go
- pkg/tarfs/tarfs.go
This was done out of a desire to use `filepath.Rel`, and force of habit, but had the unfortunate side-effect of mangling paths on Windows.
Closes: #1327
> tarfs: remove `path/filepath` usage

- libvuln/jsonblob/jsonblob.go
- libvuln/jsonblob/jsonblob_test.go
This change ensures that any updaters that implement the delta update flow also have their vulnerabilities persisted in the jsonblob store.
> libvuln: implement DeltaUpdateVulnerabilities for jsonblob store

- libindex/tempdir_unix.go
Noticed that this was preventing building on Windows.
> libindex: add complimentary build constraint

- dpkg/scanner.go
- dpkg/scanner_test.go
- dpkg/testdata/vcpkg.status
This should prevent spurious packages appearing because of these files.
Closes: #1359
> dpkg: handle vcpkg "control" files

- internal/httputil/responsechecker.go
- internal/httputil/responsechecker_test.go
- libindex/fetcher.go
We were repeating this pattern in a few places in the code and it would be a good idea to include it in other http calls to get some context about an error without having to read the whole body.
> httputil: add a ResponseChecker to be reused when making http calls

- toolkit/types/cpe/match_test.go
- toolkit/types/cpe/unbind.go
- toolkit/types/cpe/wfn_test.go
Found a case where invalid input resulted in the component being interpreted incorrect during a match. This should fix that bug.
> cpe: add additional handling for invalid URI inputs

- toolkit/types/cpe/match.go
- toolkit/types/cpe/match_test.go
It was found that when comparing individual CPE attributes where the source contains a wildcard and the target should report a Disjoint, it was being overridden with a Superset.
> cpe: avoid overwriting disjoint when using wildcards

- toolkit/types/cpe/generate.go
- toolkit/types/cpe/match.go
- toolkit/types/cpe/mkdict.go
- toolkit/types/cpe/wfn.go
- toolkit/types/cpe/wfn_test.go
This speeds up the "Dictionary" test by pre-processing the CPE XML Dictionary into a flat list structure. Doing this speeds up the test (both normal and under the race detector) by about 3x.
```
Executing: cd toolkit/types/cpe && go test -run Dict
PASS
ok      github.com/quay/claircore/toolkit/types/cpe     9.404s
```
```
Executing: cd toolkit/types/cpe && go test -run Dict
PASS
ok      github.com/quay/claircore/toolkit/types/cpe     3.872s
```
> cpe: speed up dictionary test

- .github/workflows/main.yml
- datastore/postgres/migrations/main_test.go
- datastore/postgres/migrations/matcher/13-v2-schema-meta.sql
- datastore/postgres/migrations/matcher/14-v2-schema.sql
- datastore/postgres/migrations/matcher/15-v2-import.sql
- datastore/postgres/migrations/matcher/testdata/migration_13.txtar
- datastore/postgres/migrations/matcher/testdata/migration_14.txtar
- datastore/postgres/migrations/matcher/testdata/migration_15.txtar
- datastore/postgres/migrations/migrations.go
- test/postgres/db_common.go
This is a new database schema for the `matcher` subsystem, focused on:
1. enabling queries across ecosystem silos
2. reducing write traffic during an update
3. trusting identifiers in the data instead of using client-side hashing schemes
4. bulk load via `COPY`
Explicit non-goals:
1. maintaining backwards compatibility
2. `JOIN` avoidance
TODO for this PR:
> matcher: new database schema

- rhel/vex/parser.go
There are a couple of places that append to a slice with debug information, this patch checks if debug logging is enabled before appending to save unnecessary allocation.
> vex: check if debug logging enabled before appending

- toolkit/types/cvss/cvss_v3_score.go
- toolkit/types/cvss/cvss_v3_test.go
Prior to this change, the test CVSS I added was given a score of 10.8, which is too high
> cvss: v3: fix scope multiplication placement

- rhel/repositoryscanner.go
- rhel/rhcc/scanner.go
- rhel/rhcc/updater.go
- rhel/updaterset.go
- rhel/vex/updater.go
Red Hat security data is migrating over to the new location `https://security.access.redhat.com/data`, so this PR migrates all instances of `redhat.com/security/data` over to the new one.
> rhel: update security data url domain

- rhel/vex/parser.go
In non-debug environments (and always for known-affected vulnerabilities) we carry on parsing when we don't find a relationship. This means we error at the next block and continue then but it makes the logs more confusing.
> vex: update some minor parsing logic

- .github/workflows/golang-image.yml
This change means we do not have to change this list. It also only updates upstream-supported versions; this can change back to some number of versions if desired.
> cicd: automate list of "golang" image versions

- datastore/postgres/querybuilder.go
- libvuln/driver/matcher.go
- rhel/matcher.go
As the matcher now no longer queries on repo name, it means the result set returned from the DB is a lot larger. This change limits the results to just those added by the RHEL updater (previously OVAL now VEX).
> rhel: add repo_key matching constraint

- .github/workflows/main.yml
- go.mod
- toolkit/go.mod
- updater/driver/go.mod
Updating to go1.22.7 which is/was the latest patch is not in-line with our own documentation https://github.com/crozzy/claircore/blob/main/docs/contributor/go_version.md.
> chore: align go version with docs

- rhel/vex/fetcher.go
- rhel/vex/fetcher_test.go
By switching how the VEX data is appended to the output spool we allow the parser to ignore duplicates rather than have to process things twice. This helps in situations where RH prodsec update a large number of files and haven't updated the archive data.
> vex: fetcher add changes before archived data

- alpine/parser.go
- alpine/parser_test.go
- libindex/libindex_test.go
It was brought to my attention https://security.alpinelinux.org exists, and we may find vulns in `https://security.alpinelinux.org/vuln/<CVE ID>`. For example: https://security.alpinelinux.org/vuln/CVE-2018-20187.
This is now my second time updating the link we use for Alpine vulns. I believe last time there was concern about migrations and whatnot, but I believe since then we added a materialized view when looking at the latest vulnerability data in the DB, so this may be a non-issue now. This is all to say: I do not believe I need to add a migration.
Went back to the other PR https://github.com/quay/claircore/pull/810, and it seems it was allowed after https://github.com/quay/claircore/pull/947 was merged, though I can see querybuilder.go has been updated since then.
> alpine: use alpine security vuln link

- updater/osv/osv.go
Disable more OSV ecosystems for situations where we already have a dedicated updater.
> osv: disable more ecosystems

- README.md
Refresh the README to be more in-line with the commands that exist in the Makefile. Also, bring the casing of Claircore in-line with convention (Claircore == good in prose, claircore == good in code, ClairCore == bad).
> docs: update README to remove non-existent commands

- updater/osv/osv.go
- updater/osv/osv_test.go
It was discovered that some OSV documents can order minor releases in the same affected.ranges object. This meant that only ever counted the last range in a vulnerability. This change gathers range information for the affected product and creates a vulnerability per range.
> osv: account for event objects that have multiple streams

- gobin/exe.go
- gobin/gobin.go
I pulled the binary from an OpenShift image (`/usr/bin/openshift-controller-manager`) and ran `TestBin` in `gobin/exe_test.go`:
```
stdlib@1.20.12 / 1.20.12
```
This is what I expected to see.
Previously, it was:
```
stdlib@go1.20.12 X:strictfipsruntime / 0
```
`gobin`'s matcher relies on PostgreSQL to handle the version comparison based on the `NormalizedVersion`. In this case, it'll be `1.20.12`, which is what we'd want/expect.
Note: This will change the package's version by removing the `X` flags, as they are not used at this time. The unique index for the `package` table is based on `(name, version, kind, module, arch)`. So, if we do not change the version, then instances of Clair which upgrade to a version with this change will not have the package's table modified to account for …
> gobin: ignore flags in stdlib version

- test/periodic/rpm_test.go
- test/rpmtest/manifest.go
For the RPM test we check the index report against the pyxis manifest for that image. The format of this manifest has recently changed when they started producing builds from Konflux, this change accounts for those changes.
> periodic: account for differences with Konflux built images

- rhel/dockerfile/testdata/Dockerfile-nodejs10.want
- rhel/dockerfile/testdata/Dockerfile-rhdh-rhdh-hub-rhel9-1.3-100
- rhel/dockerfile/testdata/Dockerfile-rhdh-rhdh-hub-rhel9-1.3-100.want
- rhel/dockerfile/vars.go
- rhel/dockerfile/vars_test.go
- rhel/rhcc/scanner_test.go
- rhel/rhcc/testdata/Dockerfile-rhdh-rhdh-hub-rhel9-1.3-100
This change means label values like `"$PRODNAME-$COMPNAME-container"` will be expanded to something like `"rhdh-hub-container"` instead of `""` which I think is preferred as the security data refers to "rhdh-hub-container" as the package_name.
> rhel: don't consider hyphen as valid in dockerfile ENV var names

- toolkit/types/csaf/csaf.go
- toolkit/types/csaf/csaf_test.go
I am interested in obtaining the aggregate severity of a CSAF advisory. For example: https://security.access.redhat.com/data/csaf/v2/advisories/2024/rhsa-2024_0024.json
It has an aggregate severity of `Important`. Without this change, I'd have to look at the severity rating of each vulnerability and find the highest (assuming that's how the aggregate is determined 100% of the time). With this change, it's much simpler to obtain.
> csaf: read aggregate_severity

- docs/SUMMARY.md
- docs/contributor.md
- docs/contributor/releases.md
Adding information about how to release claircore from main and from a release branch.
> documentation: add release documentation

- go.mod
According to the [Go Release policy](https://go.dev/doc/devel/release#policy) Go 1.22 is no longer supported, and things coming down the pipe will rely on 1.23's iterator support.
> chore: update to go1.23

- gobin/exe.go
- gobin/gobin.go
- gobin/gobin_test.go
Go 1.24 changes the way in which the main module's version is reported when the module is build via `go build`. What used to be just reported as `(devel)` will now be reported as the version + revision info (+dirty if status is uncommitted) unless the -buildvcs=false is set. All this means that the unit tests failed as the expected `(devel)` version wasn't found and instead "" was reported because the gobin detector doesn't set any Version if the main module's version was parseable (this isn't a big deal because the matching always works of NormalizedVersion which is always set). This change always adds the Version and the test checks the Version with the same regex `ParseVersion` uses.
> gobin: always report the main version in Package.Version

- datastore/postgres/migrations/migrations.go
- datastore/postgres/migrations/migrations_test.go
While the sql command was added to claircore (and the admin command was added to clairctl) to create an index it was never actually reference in the migrations. This should be a no-op for all instances that ran the associated clairctl admin command. Also, added a test to try and avoid this in the future.
> migrations: add missing index creating migration

- docs/SUMMARY.md
- docs/contributor.md
- docs/contributor/iter.md
As requested while catching up with some collaborators, here's some documentation on iterator patterns as I've found them. I've been using the iterators in their experimental form in Go 1.22 and so have a little more of a feel for them than most.
<details>
<summary>Rendered Output</summary>
</details>
> docs: iterator patterns

- gobin/gobin.go
- nodejs/packagescanner.go
- python/packagescanner.go
- ruby/packagescanner.go
After merging 1a72e8e2ab846a4ef08a4e4ba7829161db466be0 the package detector versions should have iterated, this commit corrects that. (Java omitted as it has been updated since).
> rpm: update package detector versions

- oracle/updaterset.go
Fixes the Oracle updater to include the current year.
Proof:
<details>
<summary>
main.go
</summary>
```go
package main
import (
"fmt"
"time"
)
func main() {
fmt.Println("Current loop:")
for year, lim := 2007, time.Now().Year(); year != lim; year++ {
fmt.Println(year)
}
fmt.Println()
fmt.Println("Fixed loop:")
for year, lim := 2007, time.Now().Year(); year <= lim; year++ {
fmt.Println(year)
}
}
```
</details>
<details>
<summary>
output
</summary>
```
Current loop:
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
Fixed loop:
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
```
</details>
Related to https://github.com/quay/claircore/issues/1419.
> oracle: inclusive year limit in updater

- duration.go
- rhel/vex/fetcher.go
- rhel/vex/updater.go
The timeout was hardcoded to 2m, this remains the default value but users have the option to configure it to a different value using `updaters.config.rhel-vex.compressed_file_timeout`.
> vex: allow timeout to pull down VEX archive to be configurable

- test/periodic/rpm_test.go
It turns out that some images are now upgrading packages in subsequent layers, this meant our process of overwriting packages with the same name should have worked but it looks like the layers are ordered in reverse when returned via the api/containers/v1/repositories/registry API.
> chore: consume layers in reverse order for rpm spotchecks

- gobin/gobin.go
- java/packagescanner.go
- nodejs/packagescanner.go
- python/packagescanner.go
- rpm/files.go
- rpm/files_test.go
- ruby/packagescanner.go
While load testing the latest version it was found that the indexing latency was drastically increase (7x was observed). After some profile/blocking analysis it was found that the volume of calls to the `FileInstalledByRPM()` function were causing lock contention due to sheer number of paths the language detectors were checking. This change addresses that issue by creating `FileChecker` object before path iteration and then using it for the subsequent paths. After this change, no perceivable latency was added as a result of the RPM file checking.
> rpm: optimize file checking operation

- .github/dependabot.yml
This option is being removed in favor of looking at the CODEOWNERS file, https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/
> chore: remove reviews from dependabot config

- dpkg/scanner_test.go
According to the log, this test is a hold-over from when tar handling code was in every scanner, so removing it should be fine.
> dpkg: remove test with missing fixture

- rhel/internal/common/updater.go
Currently ACS Scanner indexer will load the 'embedded' repository-to-cpe.json & container-name-repos-map.json and use them for 24 hours before attempting to pull the latest from Central/live URL.
This will lead to 'scanning discrepancies' when an indexer first starts up (such as when the HPA adds new replicas).
> Load latest repo2cpe/container mapping files prior to embedded

- oracle/parser.go
- oracle/parser_test.go
Oracle's OVAL data includes ksplice userspace packages that aren't supported to run in containers.
This PR changes the parsing of this data to omit ksplice-related vulnerabilities by checking the affected CPEs list. If all CPEs are all related to ksplice, we'll omit it. If there is at least one CPE that is **not** related to ksplice, we'll add all the vulnerabilities anyway, which _may_ cause us to record false positives for that vulnerability, but that case seems very unlikely.
Related to https://github.com/quay/claircore/issues/547.
> oracle: omit ksplice-related vulnerabilities

- java/packagescanner.go
This change constructs the solr search as a string field instead of a text field. Other implementations of the Cental search API seem to like it this way instead of the other.
See-also: quay/claircore#1567
> java: change search query

- test/rpmtest/manifest.go
/api/containers/v1/images/id/{img_id}/rpm-manifest now returns a lot of packages in the response for different architectures. These packages don't have any source information. This was causing test errors when trying to convert them into `claircore.Package`s. This patch ignores pacakges that don't contain full source information.
> test: discount packages without source information in rpm-manifest

- internal/cmd/mdbook-godoc/main.go
| Before | After |
|--------|--------|
| ![quay github io_claircore_reference_coalescer html](https://github.com/user-attachments/assets/2c9e3fcd-f8c7-4d26-96fb-e4f592032eb8) | ![localhost_3000_reference_coalescer html](https://github.com/user-attachments/assets/551ec266-6b16-42d8-bb83-f8f236a1f3cf) | 
| ![quay github io_claircore_reference_configurable_scanner html](https://github.com/user-attachments/assets/97c88637-99ab-415d-8b3a-407bd8ed3a70) | ![localhost_3000_reference_configurable_scanner html](https://github.com/user-attachments/assets/79b1fdec-06c2-4430-9af5-241d01391ac7) | 
Closes https://github.com/quay/claircore/issues/1574.
> docs: fix code blocks in mdbook-godoc preprocessor 

- datastore/postgres/affectedmanifest.go
- datastore/postgres/digest.go
- datastore/postgres/digest_test.go
- go.mod
pgtype is part of pgx/v5 there is no need to use legacy version.
- https://github.com/jackc/pgtype/commit/045ef2b0119074dd010d0298cd3740114d4070c0
- https://github.com/quay/claircore/pull/1530
> replace pgtype with pgx/v5 version

- internal/matcher/controller.go
- pkg/rhctag/version_test.go
- rhel/matcher.go
- rhel/matcher_test.go
- rhel/rhcc/coalescer.go
- rhel/rhcc/coalescer_test.go
- rhel/rhcc/detector.go
- rhel/rhcc/detector_test.go
- rhel/rhcc/ecosystem.go
- rhel/rhcc/matcher.go
- rhel/rhcc/rhcc.go
- rhel/rhcc/scanner.go
- rhel/rhcc/testdata/labels.schema.json
- rhel/rhcc/testdata/simple_labels.json
- rhel/vex/parser.go
- rhel/vex/updater.go
- test/rhel/rhcc_matcher_integration_test.go
- test/rhel/testdata/clair-rhel8-v3.5.5-4-labels-indexreport.json
- test/rhel/testdata/rook-ceph-operator-container-4.6-115.d1788e1.release_4.6-indexreport.json
- test/rhel/testdata/rook-ceph-operator-container-4.7-159.76b9b11.release_4.7-indexreport.json
- version.go
Red Hat's new container image builder system does not include a
dockerfile at a known path in the image, this is replaces with a file
called labels.json file at a known location that contains the
information that the rhcc package and repository scanners need. This
change adds another rhcc package and repository scanner that read this
labels.json file. The dockerfile versions still exist but will be
eventually deprecated and removed.
> rhcc: account for labels.json file

- rhel/vex/parser.go
- rhel/vex/parser_test.go
- rhel/vex/testdata/cve-2024-24786-simple.json
Red Hat prodsec have decided to move from declaring a component's RPM module in the VEX relationships to directly including the module string in the component's purl as a qualifier. This change accounts for that change (while still supporting the original logic path as it's currently split-brain).
> rhel: account for the rpmmod being included in the component's PURL

- .github/scripts/prepare-release
It was annoying as PRs that needed changelog entries were being displayed without line breaks so it was difficult to parse.
> chore: seperate line output when a release is missing changelog

- .github/workflows/prepare-release.yml
- .github/workflows/update-clair.yml
The create-pull-request action will first push a branch to the remote before creating a PR, I believe that branch push requires contents: write permissions.
> chore: add content writing permissions to GH workflows

- internal/rpm/find.go
Prior to https://github.com/quay/claircore/pull/869, the PackageDB for RPMs were prefixed with the DB kind (sqlite, bdb, or ndb). With that change, the prefix was removed. I believe this was an accident. This PR adds it back
> rpm: prefix PackageDB with kind

- .github/workflows/changelog-label.yml
The changelog label check updates the pull-request's labels so I think it needs pull-request write permissions.
> chore: update changelog label check permissions

- internal/cache/doc.go
- internal/cache/live.go
- internal/cache/live_test.go
- internal/singleflight/singleflight.go
- internal/singleflight/singleflight_test.go
This is a generic'd version of the `rpm.PathSet` cache.
Once merged, that implementation and the refcounting scheme in the fetcher can be replaced with `cache.Live`.
The package is named `cache` because we may want different cache strategies in the future, so we can just add more types here (e.g. `S3Fifo`, `LRU`).
> internal: cache package

- enricher/cvss/cvss.go
- enricher/cvss/cvss_test.go
- enricher/epss/epss.go
- enricher/epss/epss_test.go
- enricher/kev/kev.go
- enricher/kev/kev_test.go
Descriptions can often refer to different CVEs or multiple CVEs to the actual CVE that is associated to the vulnerability leading to erroneous scores. We should only consider the Name and Links fields.
> enrichment: don't consider vulnerability.Description for enrichments

- suse/factory.go
- suse/factory_test.go
Updated the SUSE OVAL source after finding https://www.suse.com/support/security/oval/. The old source no longer contains gzip versions of the OVAL files, and the files do not seem current (ex: missing the latest openSUSE leap version).
See the [README](https://ftp.suse.com/pub/projects/security/oval/README) and [LICENSE](https://ftp.suse.com/pub/projects/security/oval/LICENSE) linked in this sentence.
~I'm not sure if the older OVAL files included unfixed vulnerabilities, so I just opted to use the OVAL files which include: fixed, unaffected, and unfixed. I can switch it to exclude unfixed vulnerabilities, if desired.~
Opted to use the feeds without unfixed vulnerabilities, as we have precedent of not using that in the past - https://github.com/quay/claircore/pull/1545
> suse: update OVAL source
