Makefile, README.md, cmd/libvulnhttp/main.go, docker-compose.yaml, docs/local-dev.md, internal/scanner/postgres/teststore.go, internal/vulnstore/postgres/testvulnstore.go
A local development environment based on docker-compose.
=> Docker compose

internal/matcher/controller.go, internal/updater/controller.go, internal/vulnstore/postgres/get.go, internal/vulnstore/postgres/gethash.go, internal/vulnstore/postgres/gethash_integration_test.go, internal/vulnstore/postgres/putvulnerabilities.go, internal/vulnstore/postgres/putvulnerabilities_integration_test.go, internal/vulnstore/postgres/vulnstore.go, internal/vulnstore/updater.go, internal/vulnstore/updater_mock.go, internal/vulnstore/vulnerability.go
This commit also updates calling code to plumb contexts through.
=> vulnstore: add context.Context to interfaces

debian/matcher_integration_test.go, internal/scanner/defaultfetcher/fecher_integration_test.go, internal/scanner/postgres/indexpackage_benchmark_test.go, internal/scanner/postgres/indexpackage_test.go, internal/scanner/postgres/layerscanned_test.go, internal/scanner/postgres/manifestscanned_test.go, internal/scanner/postgres/packagesbylayer_benchmark_test.go, internal/scanner/postgres/packagesbylayer_test.go, internal/scanner/postgres/registerscanners_test.go, internal/scanner/postgres/scanreport_test.go, internal/scanner/postgres/setscanfinished_test.go, internal/scanner/postgres/setscanreport_test.go, internal/scanner/postgres/teststore.go, internal/updater/updater_integration_test.go, internal/vulnstore/postgres/gethash_integration_test.go, internal/vulnstore/postgres/putvulnerabilities_integration_test.go, internal/vulnstore/postgres/testvulnstore.go, layer_integration_test.go, test/integration/integration.go, test/integration/run.go, test/integration/skip.go, ubuntu/matcher_integration_test.go, ubuntu/updater_integration_test.go
This is based on my PR #14, so I'll merge it after that.
=> integration: add test/integration package 

pkg/distlock/postgres/distlock.go
This covers the case where the input key is less than 8 bytes long.
=> distlock/postgres: hash input key

internal/updater/controller.go
This commit makes sure the fetching machinery doesn't return an
io.ReadCloser on error paths and that the calling code doesn't
unconditionally call Close.
=> updater: don't expect to call Close on error paths

pkg/distlock/postgres/distlock.go
This PR fixes an issue where the `locked` bool in the postgres distributed lock was not flipped. Also added sync points to both TryLock and Unlock to ensure concurrent processes see a single `locked` bool value. 
We typically do not share these locks.
=> dist-lock fix

oracle/updater.go, rhel/rhel.go
PR removes one-off tmp file structs to the shared package implementation.
=> tmp.File plumbing

go.mod, go.sum
=> go.mod: update goval-parser version

cmd/libvulnhttp/updaters.go
PR plumbs in rhel updaters for the libvulnhttp dev server
=> plumb rhel into libvulnhttp

internal/vulnstore/postgres/putvulnerabilities.go
This commit splits large batch inserts into a series of bounded-size
batch inserts, and inserts them inside the created transaction, instead
of outside of it.
=> postgres: db batch fix

alpine/fetcher.go, alpine/fetcher_test.go, alpine/parser.go, alpine/parser_test.go, alpine/release.go, alpine/repo.go, alpine/secdb.go, alpine/secdb_test.go, alpine/testdata/v3_10_community_truncated.yaml, alpine/updater.go, cmd/libvulnhttp/updaters.go, go.mod, go.sum, internal/vulnstore/postgres/putvulnerabilities.go
This PR introduces the Alpine updater. 
It also fixes a small issue where pgx closes a tx on context cancelation
=> Alpine Updater

internal/vulnstore/postgres/putvulnerabilities.go, pkg/microbatch/microbatch.go
This pr implements a way to create variable sized batches for insert. 
Tuning the batch size allows for a reduction of database contention.
=> microbatching

test/integration/integration.go
Fix typo in integration package comments
=> fix typo to without

rpm/packagescanner_test.go, test/fetch/layer.go
Fixes small issues with RPM integration tests failing.
=> fix stale layer, increase layer fetch timeout

internal/indexer/fetcher/fetcher.go
Ran into this nonsensical error today. Fixed it.
=> Fetcher Error

internal/indexer/fetcher/fetcher.go, rpm/packagescanner.go
Found these while doing some testing.
=> Misc fixes

debian/matcher.go, debian/releases.go, debian/updater.go
This PR introduces Debian matching.
=> Debian Matching

internal/indexer/linux/coalescer.go
This PR fixes a bug which crashes libvuln. Previous to this patch if no distribution information was found the Coalescer would still associate the packages with a nil dist struct. When the matcher accessed a field on this nil struct it panics.
Solution here is to simply reorder the association loops and only associate a Package with a Distribution if the dist is not nil.
=> fix-nil-dists

osrelease/scanner.go
Closes: https://issues.redhat.com/browse/PROJQUAY-47
Previously to this PR an exhaustive search was not done to find an os-release file. Replace the filer usage with the layer.Reader() method of getting a Reader. Attempt to parse all files with a base-path of os-release.
=> exhaustive search for os-release

osrelease/scanner.go
This PR fixes an issue where the err value from the tar search
loop had the wrong scope.
=> Fix os-release error scope

internal/indexer/controller/controller_test.go, libindex/libindex_integration_test.go, osrelease/scanner.go, rhel/matcher_test.go, rpm/packagescanner.go, test/updater.go
In this PR fixes various bugs breaking test.
=> Various fixes which break tests

internal/indexer/postgres/indexdistributions_test.go, internal/indexer/postgres/indexpackage_test.go, internal/indexer/postgres/indexrepository_test.go, internal/indexer/postgres/manifestscanned_test.go
I goofed with some copy-paste on the previous commit.
=> postrges: fix test copy-paste errors

README.md, docs/indexer_architecture.md, docs/matcher_architecture.md
Slim the readme and point to github pages.s
s/\./\\/g
=> slim readme, dots to slashes

internal/indexer/postgres/indexpackage.go, internal/vulnstore/postgres/putvulnerabilities.go
Does what it says on the tin, and also adds some logging about what was discarded.
=> Don't persist empty packages

internal/vulnstore/postgres/get.go, libvuln/init.go, libvuln/libvuln.go
Removes additional lingering context.Background usage.
=> context hunting

cmd/cctool/report.go
As it seems that _cctool_ is aimed at replacing klar, it'd love to be able to get jUnit reports out of it. If tabwriter is nice, it doesn't integrate that well Java-minded CI. The goal here is to be able to use those report in GitLab, https://docs.gitlab.com/ee/ci/junit_test_reports.html
Let me know what you think. Using raw templates to produce XML is conceptually wrong.
=> feat: add jUnit reports to cctool

pkg/ovalutil/fetcher.go
This makes sure to check errors from creating the gzip reader, and to make sure the response body's `Close` is deferred if there's a response.
=> ovalutil: correctness fixes

test/integration/db.go
This PR simplifies the test harness's database logs
=> log info we care about

internal/indexer/controller/reduce.go, internal/indexer/layerscanner/layerscanner.go
=> the empty layer

internal/indexer/layerscanner/layerscanner.go
De-duplicate the work whens scanning layers.
=> dedupe layers to be scanned

dpkg/scanner.go
This pr fixes an issue where the dpkg scanner chocked
on a valid EOF
=> fix tar eof

internal/vulnstore/postgres/get.go, internal/vulnstore/postgres/querybuilder.go, internal/vulnstore/postgres/querybuilder_test.go
This PR SELECTS normalized_severity when scanning a vulnerability
=> Normalized Severity Fix

digest.go
PR implements a method suitable for construction
digests in test tables and struct literals
=> Must Parse Digest

internal/vulnstore/postgres/getupdateoperations.go
This should fix a segfault when hitting this error case.
=> postgres: defer after checking error

libvuln/updaters.go, ubuntu/releases.go, ubuntu/updaterset.go
Ditch unsupported updaters to cleanup noisy logger
=> Ditch Ubuntu Updaters

libvuln/updatesets.go
This PR adds missing updater sets to the defaults in libvuln
=> Add default update sets

docs/severity_mapping.md
=> docs: mention pyupio updater

Makefile, etc/.gitignore, etc/podman.yaml.in
=> Makefile: use podman play for podman env

.github/workflows/main.yml
This PR puts a pull_request event on our github actions. Right now they do not trigger on pull requests from a fork.
=> add on-pr event

libvuln/migrations/migration1.go, rhel/matcher.go
This PR tunes the vulnerability table index back to a state which performs well.
=> re-tune indexes

libvuln/opts.go, oracle/matcher.go, suse/matcher.go
- Implemented Matcher interface for Oracle and SUSE packages
- Added Oracle and SUSE to default Matcher options
@ldelossa
=> Implemented Matcher for Oracle and SUSE

internal/vulnstore/postgres/get.go
When package is associated with multiple repositories a database query
returns duplicated vulnerability. This function only appends
vulnerability when it is no present in slice.
=> De-duplicate list of vulnerabilities

rhel/updaterset.go
=> rhel: fix config struct tag

go.mod, go.sum
=> goval: bump goval for ubuntu date fix

.github/workflows/main.yml, Makefile, docker-compose.yaml
=> testing: bump golang 1.15 local dev

.github/workflows/main.yml
=> cicd: fix commit check regexp

.github/workflows/main.yml
=> cicd: force no flags for regexp commit check

rhel/repo2cpe/updater.go
=> repo2cpe: add errorchecking

.github/workflows/main.yml, .github/workflows/prepare-release.yml, .github/workflows/release.yml
=> cicd: copy some changes from clair's CI workflows

rpm/packagescanner.go
=> rpm: fix error handling in WalkFunc

alpine/matcher.go, go.mod, go.sum
this commit adds an apk specific version parser for alpine matcher.
Closes: #254
=> matcher: add apk specific version parser for alpine

go.mod, go.sum, pkg/ovalutil/dpkg.go, pkg/ovalutil/error.go, pkg/ovalutil/rpm.go, pkg/ovalutil/test.go, test/ovaldebug/main.go
=> ovalutil: update vulnerability heuristic

.github/workflows/prepare-release.yml
=> cicd: bump create pull request action

pkg/ovalutil/dpkg.go, pkg/ovalutil/rpm.go
this commit re-evaluates the rpm and dpkg oval structures and updates
the parsing logic.
=> oval: rpm and dpkg parser updates

dpkg/scanner.go, dpkg/scanner_test.go
This adds stricter checks to discovered paths that seem to be dpkg
metadata files. Instead of just using a discovered string in a map
lookup, the Scanner now validates the path better and does a checked
lookup in the map.
Fixes PROJQUAY-1308.
=> dpkg: add checks to discovered paths

docs/concepts/severity_mapping.md, photon/normalizeseverity.go, photon/parser.go
Add normalized severity to vulnerabilities related to Photon OS
=> photon: add normalized severity

alpine/ecosystem.go
=> alpine: fix typo of ecosystem

test/fetch/layer.go
I'd like to add onto this PR to ultimately make it so that we're talking to quay.io for integration tests, and this is the first step.
=> fetch: turn layer fetcher into a generic fetcher

docs/getting_started/libvuln_usage.md, internal/vulnstore/updater.go, libvuln/libvuln.go, libvuln/opts.go
=> docs: various doc fixups

docs/concepts/severity_mapping.md, internal/matcher/matcher_mock.go, internal/vulnstore/updater_mock.go, severity.go, severity_string.go
Defcon1 is a manual severity only used by the quay team. It is being depreciated from Quay hence removing from Quay
=> PROJQUAY-586 - Remove Defcon1 severity

libvuln/updates/manager.go
when moving libvuln to non-blocking the initial updater run was removed.
this caused libvuln not to issue a run of the update manager until the
first interval tick which by default is 30 minutes.
this update adds a implicit call to run before setting up the
time.Tickers.
=> updates: perform implicit run

.github/workflows/prepare-release.yml
=> cicd: filter tags for stable branch releases

.github/workflows/prepare-release.yml
=> cicd: fix gh action script

.github/workflows/prepare-release.yml
=> cicd: gh action echo branch

alpine/distributionscanner.go, aws/distributionscanner.go, debian/distributionscanner.go, oracle/distributionscanner.go, photon/distributionscanner.go, rhel/distributionscanner.go, suse/distributionscanner.go, ubuntu/distributionscanner.go
Signed-off-by: RTann <ross@stackrox.com>
=> chore: update comments in distribution scanners

internal/vulnstore/postgres/getupdateoperationdiff.go
small optimization seems to shave ~800ms off our largest update diff
query.
=> vulnstore: update-diff optimize

.chglog/config.yml, .github/workflows/prepare-release.yml, .github/workflows/release.yml
git-chglog pr which implements semver sorting
has been merged.
=> cicd: remove chglog fork

libvuln/jsonblob/jsonblob.go
Fix for some bugs Louis spotted while doing enricher work.
Co-authored-by: ldelossa <ldelossa@redhat.com>
=> jsonblob: fix copyops

.github/scripts/get-latest-golang-minor-version.sh, .github/workflows/golang-image.yml, etc/Dockerfile
This PR has been opened to replace https://github.com/quay/clair/pull/1159. For full description, se the original PR. See https://github.com/quay/clair/issues/1156 for justification of this effort.
=> cicd: add golang-image workflow

libvuln/driver/enrichment.go
=> enrichment types and interfaces

CODEOWNERS
same as https://github.com/quay/clair/pull/1285
If you really need me, you can mention me and I'll actually notice.
=> all: remove jzelinskie from CODEOWNERS

internal/indexer/controller/checkmanifest.go
If the manifest has prevously been scanned it significantly
decreases the time it takes to create an index_report. This a
a useful metrics when analyzing response latencies.
=> introspection: add scanned_before metrics

internal/indexer/fetcher/fetcher.go
I'm currently debugging a particularly baffling error where Clair gets a 403 when trying to fetch layers, but curl on the same URL gets a 200. It would help me to see what actual error (beyond the status code) Clair is getting, so this change exposes the error message from the HTTP response in the returned error.
=> fetcher: include response body in error message for non-200 repsonses

rpm/packagescanner.go
This should error out earlier in the process and uses some extra tar
flags to make the permissions more amenable.
=> rpm: eagerly change directory permissions

rpm/packagescanner.go, rpm/packagescanner_test.go
=> backport: rpm fixes

java/common.go, java/packagescanner.go
This change looks at the magic number if something appears to be a jar
based on the filename.
Closes #434
=> java: check magic number

.github/scripts/prepare-release
This is a less terse version of a shortcut that I stuck into my git
aliases.
=> scripts: check in a prepare-release script

java/common.go, java/packagescanner.go
=> Backport 0.5: java

rpm/packagescanner.go
=> Backport 0.5: rpm

rpm/packagescanner.go
This fixes a bug where links would be created to unprefixed paths, which
would not exist and would fail at the link fixup step.
See-also: https://issues.redhat.com/browse/PROJQUAY-2403
=> rpm: normalize link target

rpm/packagescanner.go
This fixes a bug where links would be created to unprefixed paths, which
would not exist and would fail at the link fixup step.
Backports: #447
See-also: https://issues.redhat.com/browse/PROJQUAY-2403
=> backport 0.5: rpm: normalize link target

rpm/packagescanner.go
This fixes a bug where links would be created to unprefixed paths, which
would not exist and would fail at the link fixup step.
Backports: #477
See-also: https://issues.redhat.com/browse/PROJQUAY-2403
=> backport 0.4: rpm: normalize link target

internal/indexer/layerscanner/layerscanner.go, java/packagescanner.go, rpm/packagescanner.go
Some error handling bits I've spotted.
=> Errhandling

.github/workflows/golang-image.yml, .github/workflows/main.yml, docker-compose.yaml
=> chore: update go versions

rpm/packagescanner.go
Would it surprise you, dear reader, to know we haven't seen this in our
use and testing?
=> rpm: handle cross-layer hardlinks when extracting

rpm/packagescanner.go
This should allow us to cut down on false positives.
=> rpm: examine file for BDB magic numbers

.chglog/CHANGELOG.tpl.md, .github/dependabot.yml, .github/workflows/prepare-release.yml, .github/workflows/release.yml
=> cicd: update release workflows for branch, tag changes

.chglog/config.yml
This will cope with multiple colons in the title.
=> chore: update changelog config

java/jar/jar.go, test/packagescanner.go
Ivan found a jar in the wild that doesn't have filesystem semantics.
Instead of entries `a/` and `a/b`, it contains `a` and `a/b`. This
tricks the zip package into synthesizing a file entry that cannot be
opened.
A long-term solution would be to ditch the use of the fs package inside
this package, but this does make testing a bit more complicated.
=> jar: handle archive without filesystem semantics

crda/remotematcher.go
=> crda: fix typo

go.mod, go.sum, libvuln/libvuln.go, libvuln/libvuln_test.go
=> libvuln: print documentation links with matcher names

libindex/init.go
=> libindex: treat ConnString same as libvuln

libindex/fetcher.go, libindex/fetcher_test.go
This changes the ordering around the refcount, singleflight, and file on
disk. This should prevent some file open/remove races.
An alternative fix would perhaps be to return an *os.File instead of the
file name and have the proxy dup it.
=> libindex: change ordering

rhel/repositoryscanner.go
=> rhel: tolerate invalid CPEs

go.mod, libindex/init.go, libvuln/opts.go, pkg/poolstats/collector.go, pkg/poolstats/collector_test.go
Fixes #554 
Signed-off-by: Iain Duncan <iain.duncan@uk.ibm.com>
=> Add Prometheus Collector to pgx pools

rhel/dockerfile/dockerfile.go, rhel/dockerfile/testdata/Dockerfile-InvalidLabel.want.err, rhel/dockerfile/testdata/Dockerfile-etcd-rhel7, rhel/dockerfile/testdata/Dockerfile-etcd-rhel7.want
=> dockerfile: support invalid label syntax

.github/scripts/get-latest-golang-minor-version.sh, .github/workflows/golang-image.yml, .github/workflows/main.yml, Makefile, etc/Dockerfile
updates CI for the go version change, and some QoL for future updates.
=> go versions

enricher/cvss/cvss_test.go
Go 1.18 introduced a new `vet` error for using `%w` in a testing log
format string. This fixes that and the various lints in the file.
=> cvss: fix vet errors, lints

.github/workflows/updater-check.yml, test/periodic/doc.go, test/periodic/enricher_test.go, test/periodic/periodic_test.go, test/periodic/updater_test.go
This also sets up a CI to trigger them weekly.
=> periodic: add package for periodic tests

internal/vulnstore/postgres/enrichment.go
=> postgres: update metrics on GetEnrichment

crda/remotematcher.go
This should provide more feedback on errors returned from the CRDA
API.
=> crda: check response status code

pkg/ovalutil/fetcher.go
=> ovalutil: remove pointless log

rhel/rhcc/scanner.go
This unwanted behavior was pointed out by @jvulgan.
=> rhcc: don't fatally error on unexpected Dockerfiles

ubuntu/updater.go
=> ubuntu: update feed URLs

pkg/ovalutil/dpkg.go, pkg/ovalutil/dpkg_test.go
=> ovalutil: sanity-check incoming dpkg version strings

pkg/tarfs/tarfs.go, pkg/tarfs/tarfs_test.go
Previously, the package didn't consider ordering between directories,
their children, and symlinks. For example, given the following
archive:
- z/
- z/b
- a → z
If the archive producer walks and then sorts the input files then
deduplicates by inode, the resulting order is:
- a → z
- a/b
- z/
These edge cases are now handled, along with other edge cases that
arise from resolving symlinks.
=> tarfs: resolve symlinks when adding new files

datastore/postgres/enrichment.go
Fixes #649
Signed-off-by: Iain Duncan <iain.duncan@uk.ibm.com>
=> postgres: Observe metric

.github/workflows/updater-check.yml
=> cicd: ensure rpm is installed for periodic tests

.github/workflows/golang-image.yml, .github/workflows/main.yml
=> chore: enable go1.19 building and testing

pkg/tarfs/parse.go
The code had assumed that `io.EOF` was returned with no data, which is not how `io.ReaderAt` is documented.
=> tarfs: handle data and EOF return

java/jar/jar.go, java/jar/testdata/malformed-manifests/bad-header
=> jar: handle manifest with invalid header keys

pkg/tarfs/tarfs.go, pkg/tarfs/tarfs_test.go
Found layers in the wild that need hard links. These changes implement them.
Closes: #712
=> tarfs: implement hard links

pkg/tarfs/tarfs.go
The previous change just hacked names into place. This change adds additional nodes -- ensuring that they're linked correctly -- and then has `Open` dereference them correctly.
Closes: quay/claircore#714
=> tarfs: implement hard links correctly

enricher/cvss/cvss.go, java/jar/errors.go, pkg/ovalutil/fetcher.go, rhel/repositoryscanner.go, rhel/rhcc/scanner.go, rpm/internal/rpm/header.go, rpm/internal/rpm/rpm_tag.go, rpm/packagescanner.go, ubuntu/updaterset.go
Did a pass making panic messages a bit more useful, and adding logging around a panic seen in the wild.
=> panic message improvements

rpm/extract.go
This change should eliminate some errors when tar members are present multiple times in the same archive. The OCI Image specification says layers SHOULD be sorted and deduplicated, but it's not required.
Closes: #735
=> rpm: handle existing files better

.github/workflows/golang-image.yml, etc/Dockerfile
This PR will add ppc64le support to the [quay.io/projectquay/golang](quay.io/projectquay/golang) image.
=> feature: added ppc64le support to golang base image

gobin/gobin.go, gobin/gobin_test.go
This change catches EOF errors as empty files will throw them.
=> gobin: Don't error out on EOF

.github/scripts/changelog-edit, .github/scripts/changelog-setup
This also makes the edit script a bit more resilient.
=> chore: add changelog-setup script for devs

java/metrics.go, java/packagescanner.go
=> java: add metrics for maven search API

.github/scripts/prepare-release, .github/workflows/prepare-release.yml, .github/workflows/release.yml
=> chore: update some scripts for new changelog

java/packagescanner.go
maven package search http request timeout made configurable.
=> java: maven http request timeout added

rpm/extract.go, rpm/packagescanner.go
This should reduce processing time and space requirements when handling rpm-containing layers.
=> rpm: filter layer contents when extracting

rhel/rhcc/updater.go
This attempts to use a compressed version of the file instead of just relying on transfer compression.
Closes: PROJQUAY-5053
=> rhcc: check for bzip compressed cvemap.xml

datastore/postgres/matcher_store.go, datastore/postgres/updatevulnerabilities.go
Deleting a pass-thru function that seems to obfuscate the code a little.
=> matcher: Remove unneeded pass-thru function

alpine/updater.go, aws/releases.go, book.toml, crda/remotematcher.go, debian/updater.go, docs/SUMMARY.md, docs/concepts/indexer_architecture.md, docs/concepts/matcher_architecture.md, docs/concepts/updater_defaults.md, docs/contributor.md, docs/contributor/misc.md, docs/injecturls.go, enricher/cvss/cvss.go, java/packagescanner.go, oracle/updater.go, photon/photon.go, pyupio/updater.go, rhel/repositoryscanner.go, rhel/rhcc/scanner.go, rhel/rhcc/updater.go, rhel/updaterset.go, suse/suse.go, ubuntu/updaterset.go, updater/osv/osv.go
This adds and then uses a helper to extract URLs from go source directly into documentation.
=> URL documentation helper

.github/workflows/golang-image.yml, etc/Dockerfile
Support for s390x
- added `linux/s390x` platform in **golang-image.yml** workflow file
- added **arch s390x** in **etc/Dockerfile**
=> feature: added s390x support

test/periodic/updater_test.go
It will be nice to have this so we can surface issues early.
=> osv: Add osv UpdaterSet to the periodic test suite

updater/osv/osv.go
This commit makes the OSV updater actually bother to fix non-canonical version ranges, instead of just complaining about them into the log.
=> osv: canonicalize ranges

datastore/postgres/updatevulnerabilities.go, gobin/coalescer.go, gobin/ecosystem.go, gobin/exe.go, gobin/gobin.go, gobin/matcher.go, matchers/defaults/defaults.go, pkg/omnimatcher/omnimatcher.go, updater/osv/osv.go
This enables `gobin` discovered Packages to appear in index reports and get matched.
=> gobin: enable matching machinery

python/reposcanner.go
This is a nit that looks like a copy paste error.
=> python: Update interface adherence checks

oracle/distributionscanner.go, oracle/distributionscanner_test.go, oracle/releases.go
I also created a ticket to track us potentially adding automatic updates for this in the future: https://issues.redhat.com/browse/PROJQUAY-5594
=> oracle: support oracle linux 9

rpm/sqlite/sqlite_test.go
Running this test when the testdata directory is write-protected produced spurious test failures.
Compare and contrast:
```
% function runtest() {(
set -e
d=$(mktemp -d)
pushd "$d"
trap 'popd && rm -rf "$d"' EXIT
go mod init example
printf 'package main\nimport _ "github.com/quay/claircore/rpm/sqlite"\nfunc main() {}\n' > main.go
go get -t github.com/quay/claircore/rpm/sqlite
test -n "$1" && {                                                                       
go mod edit -replace "github.com/quay/claircore=github.com/hdonnay/claircore@$1"
}                                           
go mod tidy
go test github.com/quay/claircore/rpm/sqlite
); }
% runtest
/tmp/tmp.8zn6sqeJXC ~cl
go: creating new go.mod: module example
go: added github.com/dustin/go-humanize v1.0.1
go: added …
```
=> sqlite: fix test when run from external module

rpm/native_db.go, rpm/packagescanner.go, rpm/packagescanner_test.go, rpm/testdata/nodejs.rpm-manifest.json, test/rpmtest/manifest.go
The way we handle the "module" data out of `rpm` regressed.
=> rpm: module name

updater/osv/osv.go
When parsing ecosytems.txt and removing versions we record duplicates. Currently, the code will attempt to add these as duplicate updaters and return an error, however the error is not checked. Therefore this change won't actually change the behaviour of the osv updater but rather improve the logging.
=> osv: Dedupe ecosystems

docs/SUMMARY.md, docs/contributor.md, docs/contributor/tests.md
=> docs: add section for tests

.github/scripts/get-latest-golang-minor-version.sh
=> cicd: account for the new toolchain versioning

datastore/postgres/get.go, datastore/postgres/querybuilder.go, datastore/postgres/querybuilder_test.go
By looking up the relevant update_operations (i.e. the latest ones) at the beginning of the vulnerability lookups we can avoid using the more expensive latest_vuln view.
=> datastore: Pre-lookup valid update_operations before querying

datastore/postgres/get.go, datastore/postgres/querybuilder.go, datastore/postgres/querybuilder_test.go
Looking at the query planner, this `JOIN` should actually speed things up.
=> postgres: rework query with join

book.toml, docs/contributor/misc.md, docs/godoc.go, docs/injecturls.go, docs/make_target.go, internal/cmd/mdbook-godoc/main.go, internal/cmd/mdbook-injecturls/main.go, internal/cmd/mdbook-make_target/main.go, internal/mdbook/mdbook.go
These changes move the mdbook common code into a dedicated package, then moves the commands to dedicated packages.
=> mdbook improvements

go.mod, go.sum
This updates the toolkit module to v1.1.1, which includes a small fix.
=> chore: update toolkit to latest version

test/periodic/rpm_test.go, test/rpmtest/manifest.go
This adds a layer of hierarchy to the tests to allow for adding more patterns.
See-also: PROJQUAY-5293
=> periodic: add additional search patterns

rhel/rhcc/matcher_integration_test.go
This was intended to not reach out to the Internet, but it ended up doing so. This fixes the test to only talk to the testing server as intended.
Closes: #1103
=> rhcc: fix leaky integration test

gobin/gobin.go
These are the only ELF files that would have go module information in them, anyway. Go does not use ELF relocatable objects for linking.
=> gobin: screen for ELF executables and shared objects

rpm/native_db.go, test/periodic/rpm_test.go, test/rpmtest/manifest.go
=> rpm: support "new" signatures

.github/workflows/check-fast-forward.yml, .github/workflows/fast-forward.yml
This should allow us to merge correctly from the web UI.
=> cicd: add `/fast-forward` command

alpine/distributionscanner.go, alpine/parser_test.go, alpine/release.go, alpine/updater.go
Followup to #1091 to support Alpine edge vulnerabilities
=> alpine: support edge vulnerabilities

test/periodic/rpm_test.go
=> periodic: Close created Layers

test/integration/embedded.go
Note that the GitHub CI doesn't use this path, so it's not caught in our testing.
=> integration: fix race in embedded DB setup

java/matcher.go
It's hard to debug this when I don't know the vulnerability's name
=> java: update matching error with vuln name

nodejs/matcher.go, nodejs/matcher_integration_test.go, nodejs/testdata/indexreport-splunk-8.2.6.json, updater/osv/osv.go
This requires https://github.com/quay/claircore/pull/1214 to be merged first
=> nodejs: vuln matching support

java/packagescanner.go, java/packagescanner_test.go
There's logic in the Java package scanner to disable reaching out to the internet, but we currently set a default API endpoint during `Configure` to prevent that condition. These changes introduce a `DisableAPI` flag to allow the deactivation of the fetching from the public Maven API.
=> java: allow deactivation of Maven API fetching

etc/debug/README.md, etc/debug/bin/check-alpine, etc/debug/bin/check-oval, etc/debug/bin/check-rhcc, etc/debug/lib/jq/alpine.jq, etc/debug/lib/jq/claircore.jq
Add some scripts I cooked up while investigating some Alpine stuff.
May need more documentation in the prose documentation?
=> debug: add some debugging bits

.github/dependabot.yml
Added some groups for modules that tend to move in unison.
=> cicd: add some dependabot grouping

nodejs/packagescanner.go
When testing, we ran into empty package.json files. The ruby package scanner skips invalid gems, so I figure we should skip invalid package.json files
=> nodejs: skip invalid package.json

java/jar/jar.go, java/jar/jar_test.go
Hopefully this makes some errors more comprehensible.
=> bug: extremely odd zip returning unexpected errors

toolkit/types/csaf/csaf.go, toolkit/types/csaf/csaf_test.go, toolkit/types/csaf/testdata/cve-2021-0084.json, toolkit/types/csaf/testdata/cve-2024-22047.json, toolkit/types/csaf/testdata/rhsa-2022-0011.json
Adding the ability to reason with CSAF data and some methods to trawl through the objects.
=> toolkit: add CSAF type and helper methods

libvuln/jsonblob/jsonblob.go
Trying to fix large memory usage when loading vulnerabilities
=> Fix jsonblob memory usage

docs/SUMMARY.md, docs/contributor/go_version.md
Document the recently agreed policy regarding go versions.
=> docs: add Go Version section

datastore/postgres/updatevulnerabilities.go
Previously the `update_operation` row was created outside the transaction which created vulns associated with that update_operation. This meant other updaters could refresh the `latest_update_operation` materialized view, making the new `update_operation` used for reporting before any of it's vulns were committed.
The upshot was a window where **vulnerability reports could give false-negatives** for a short period (they couldn't see any vulns associated with the most recent `update_operation`, because those vulns hadn't been committed yet).
We've seen these false-negative reports for Debian images (updater: `debian/updater`), possibly because that's an updater for a source with a large number of vulns. The window from _`update_operation` row create_ --> _vulns committed_ would be larger …
=> datastore: avoid update_operation timing window by creating in txn

libvuln/jsonblob/diskbuf_linux.go
=> jsonblob: undo overzealous use of decade-old kernel feature

layer.go, layer_test.go
To enable mounting of node filesystems, a new MediaType, application/x.filesystem+uncompressed, is introduced. The naming follows RFC6838 standards.
As the fileystem does not provide a ReaderAt, the Reader function has been updated with a check to return an error if the layer does not have a ReaderAt.
This is tracked by https://issues.redhat.com/browse/ROX-22259
=> layer: add filesystem MediaType

alpine/updater.go, docs/concepts/indexer_architecture.md, docs/concepts/matcher_architecture.md, indexer/controller/controller.go, indexer/layerscanner.go, libvuln/libvuln.go, libvuln/options.go, libvuln/updates/options.go, linux/coalescer.go, linux/coalescer_test.go, manifest.go, matchers/options.go, oracle/updater.go, pkg/ctxlock/ctxlock.go, pkg/ovalutil/fetcher.go, pkg/pep440/version.go, rhel/coalescer.go, rhel/coalescer_test.go, rhel/rhcc/rhcc.go, rpm/bdb/bdb.go, rpm/ndb/ndb.go, rpm/ndb/package.go, test/scanner.go, updater/driver/v1/interfaces.go, updater/interfaces.go
=> all: spelling

nodejs/matcher_integration_test.go
This started failing for no apparent reason. This changes the test to work by looking for known-present IDs.
=> nodejs: fix integration test

toolkit/types/csaf/csaf.go, toolkit/types/csaf/csaf_test.go
We will need to start looking up products from the threat object so add a helper method to make it easier.
=> csaf: add FindThreat() method

go.mod, go.sum
Need to update to take advantage of the new method.
=> chore: update toolkit to v1.2.2

datastore/postgres/get.go
There is a possiblity that if the index record is referring to the same package but different repositories and the Query() function isn't adding a matcher constraint for the repository, queries to the DB can end up being identical. This patch makes sure that the same query is only executed once by caching the results and using them for subsequent calls.
=> matcher: cache query results for the same query

rhel/vex/fetcher.go
Moving to the new security domain has surfaced an issue with keeping the changes.csv connection open long enough for it to be reset-by-peer. This change buffers the response to file before reading it.
=> vex: buffer changes.csv response

.github/workflows/main.yml, go.mod, toolkit/go.mod, updater/driver/go.mod
=> chore: update go version to go1.22.7

osrelease/scanner.go, osrelease/testdata/EmptyKey.txtar
We hadn't run into this before. This seems like the sensible action to take when there's no value.
=> osrelease: handle completely empty keys

java/jar/jar.go, java/packagescanner.go
Some JAR files start off with a bash script, so the header may not quite match the ZIP magic number(s). This is ok, and it's still a valid JAR. The Go standard library accounts for this, too, and it can still parse these JARs. So, this PR removes the header check, and it just lets the standard library do its thing.
It'd be great to not copy/paste this stuff in both pacakgescanner.go and jar.go. Where would the best place be to track removing this duplication?
Tested with a JAR file which starts with a bash script, and we can parse it now.
=> java: remove header check

rhel/dockerfile/unquote_test.go
I had this test file hanging around, so here it is cleaned up and committed.
=> dockerfile: add unquote tests

internal/rpm/find.go
This attempt to make the API impossible to misuse had some horrific, unintended side-effects for memory consumption, so remove it.
=> rpm: fix use of `unique.Handle` pinning `fs.FS`

datastore/postgres/enrichment.go
The new query is in "normal" `JOIN`-and-`WHERE` form and does not use the `latest_update_operations` view. In testing, this was much quicker to execute.
=> postgres: better GetEnrichments query
